package wasmo:testing;

package local:maths {
  interface calculator {
    multiply: func (a: s64, b: s64) -> s64;
  }
}

world wasmo-testing {
  export local:maths/calculator;
  export sum: func (a: s64, b: s64) -> s64;
}
