steps:
  - label: ":gradle: Publish"
    commands:
      - "cat .buildkite/gradle.properties >> gradle.properties"
      - "gradle publishAndReleaseToMavenCentral"
    plugins:
      - docker#v5.13.0:
          image: wasmo/brevity-ci@sha256:62dff340c59e68caff71be91045918ae84f2c95b414a1fa385d92c5503157f88
          run: ci-build
          environment:
            - "ORG_GRADLE_PROJECT_mavenCentralUsername"
            - "ORG_GRADLE_PROJECT_mavenCentralPassword"
            - "ORG_GRADLE_PROJECT_signingInMemoryKey"
      - docker-login#v3.0.0:
          username: wasmo
          isolate-config: false
    secrets:
      ORG_GRADLE_PROJECT_mavenCentralUsername: SONATYPE_CENTRAL_USERNAME
      ORG_GRADLE_PROJECT_mavenCentralPassword: SONATYPE_CENTRAL_PASSWORD
      ORG_GRADLE_PROJECT_signingInMemoryKey: GPG_SECRET_KEY
      DOCKER_LOGIN_PASSWORD: DOCKER_LOGIN_PASSWORD
