package dev.wasmo.brevity.integration

import dev.wasmo.brevity.kotlin.generator.WitBridgeGenerator
import dev.wasmo.brevity.withIssueCollector
import kotlin.time.Duration.Companion.milliseconds
import kotlin.time.TimeSource
import kotlinx.coroutines.CoroutineName
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.async
import kotlinx.coroutines.coroutineScope
import kotlinx.coroutines.launch
import kotlinx.coroutines.withContext
import okio.Buffer
import okio.FileSystem
import okio.Path
import okio.Path.Companion.toPath
import okio.source

/**
 * Generate a bunch of code:
 *  - `.wit`
 *  - `.kt` manually with string templating
 *  - `.rs` manually with string templating
 *  - `.kt` via Brevity
 *
 * Then compile and execute the generated code to confirm that types are bridged correctly.
 *
 * This uses the Kotlin Toolchain.
 * https://kotlin-toolchain.org/latest/
 *
 * This requires Brevity artifacts are published to Maven Local.
 *
 * ```
 * ./gradlew publishAllPublicationsToMavenLocalRepository
 * ```
 */
class BrevityExecutionTester(
  val fileSystem: FileSystem = FileSystem.SYSTEM,
  val name: String,
  val types: List<SampleType>,
) {
  private val layout = ProjectLayout(
    path = "build/BrevityExecutionTester/$name".toPath(),
  )

  suspend fun execute() {
    clean()

    coroutineScope {
      val kotlinToolchain = launch {
        launch { generateKotlinProject() }
        launch { generateApiKotlinModule() }
        launch { generateGuestAppKotlinModule() }
        launch { generateHostAppKotlinModule() }
      }

      val wit = launch {
        WitTarget(fileSystem, layout, types).generate()
      }
      val brevityKt = launch {
        wit.join()
        generateBrevity()
      }

      val hostKt = launch {
        HostKotlinTarget(fileSystem, layout, types).generate()
      }
      val hostKtJar = async {
        brevityKt.join()
        hostKt.join()
        kotlinToolchain.join()
        compileKotlinHost()
        "build/tasks/_host_executableJarJvm/host-jvm-executable.jar"
      }

      val guestKt = launch {
        GuestKotlinTarget(fileSystem, layout, types).generate()
      }
      val guestKtWasm = async {
        // Don't run The Kotlin Toolchain in parallel; that's currently broken at the moment.
        // https://kotlinlang.slack.com/archives/C062WG3A7T8/p1787598848694559
        hostKtJar.await()

        brevityKt.join()
        guestKt.join()
        kotlinToolchain.join()
        compileKotlinGuest()
        "build/tasks/_guest_linkWasmWasi/guest.wasm"
      }

      val guestRsToml = launch {
        generateGuestAppRustCargoToml()
      }
      val guestRs = launch {
        GuestRustTarget(fileSystem, layout, types).generate()
      }
      val guestRsWasm = async {
        guestRs.join()
        guestRsToml.join()
        compileRustGuest()
        "rust/target/unbundled/unbundled-module0.wasm"
      }

      launch {
        executeKotlinHost(
          "executeKotlinHost(guest=kt)",
          hostKtJar.await(),
          guestKtWasm.await(),
        )
      }

      launch {
        executeKotlinHost(
          "executeKotlinHost(guest=rs)",
          hostKtJar.await(),
          guestRsWasm.await(),
        )
      }
    }
  }

  /**
   * Delete sources generated by this tester, but no build tool outputs. Not deleting build tool
   * outputs speeds up the build.
   */
  private suspend fun clean() {
    executeIo("clean") {
      cleanRecursively(layout.path)
    }
  }

  private fun cleanRecursively(dir: Path) {
    when (dir.name) {
      "build", "target" -> return
    }

    val children = fileSystem.listOrNull(dir) ?: listOf()
    for (child in children) {
      val suffix = child.name.substringAfterLast('.', "")
      when (suffix) {
        "kt", "rs", "toml", "yaml", "wit" -> fileSystem.delete(child)
        else -> cleanRecursively(child)
      }
    }
  }

  suspend fun generateBrevity() {
    executeIo("generateBrevity") {
      withIssueCollector {
        val generator = WitBridgeGenerator.precompile(
          fileSystem = fileSystem,
          packageDirectories = listOf(layout.wit),
        ) ?: return@withIssueCollector

        for (fileSpec in generator.api.generate()) {
          fileSpec.writeTo(layout.apiSrc.toFile())
        }
        for (fileSpec in generator.guest.generate()) {
          fileSpec.writeTo(layout.guestSrc.toFile())
        }
        for (fileSpec in generator.host.generate()) {
          fileSpec.writeTo(layout.hostSrc.toFile())
        }
      }
    }
  }

  suspend fun generateKotlinProject() {
    executeIo("generateKotlinProject") {
      fileSystem.createDirectories(layout.path)
      fileSystem.write(layout.path / "project.yaml") {
        writeUtf8(
          """
          |modules:
          |  - ./api
          |  - ./guest
          |  - ./host
          |
          """.trimMargin(),
        )
      }
    }
  }

  suspend fun generateApiKotlinModule() {
    executeIo("generateApiKotlinModule") {
      fileSystem.createDirectories(layout.api)
      fileSystem.write(layout.api / "module.yaml") {
        writeUtf8(
          """
          |product:
          |  type: kmp/lib
          |  platforms: [jvm, wasmWasi]
          |
          |settings:
          |  kotlin:
          |    version: 2.4.0
          |  jvm:
          |    jdk:
          |      version: 25
          |
          |repositories:
          |  - mavenLocal
          |
          |dependencies:
          |  - com.squareup.okio:okio:3.16.4
          |  - dev.wasmo.brevity:brevity:0-testing
          |  - dev.wasmo.brevity:brevity-wasi-p1:0-testing
          |  - dev.wasmo.brevity:brevity-wasi-p2:0-testing
          |
          |dependencies@jvm:
          |  - com.dylibso.chicory:runtime:1.7.5
          |
          """.trimMargin(),
        )
      }
    }
  }

  suspend fun generateGuestAppKotlinModule() {
    executeIo("generateGuestAppKotlinModule") {
      fileSystem.createDirectories(layout.guest)
      fileSystem.write(layout.guest / "module.yaml") {
        writeUtf8(
          """
          |product:
          |  type: wasm-wasi/app
          |
          |settings:
          |  kotlin:
          |    version: 2.4.0
          |  jvm:
          |    jdk:
          |      version: 25
          |
          |repositories:
          |  - mavenLocal
          |
          |dependencies:
          |  - ../api
          |  - com.squareup.okio:okio:3.16.4
          |  - dev.wasmo.brevity:brevity:0-testing
          |
          """.trimMargin(),
        )
      }
    }
  }

  suspend fun generateGuestAppRustCargoToml() {
    executeIo("generateGuestAppRustCargoToml") {
      fileSystem.createDirectories(layout.rust)
      fileSystem.write(layout.rust / "Cargo.toml") {
        writeUtf8(
          """
          |[package]
          |name = "brevity-testing"
          |version = "0.1.0"
          |edition = "2024"
          |
          |[dependencies]
          |wit-bindgen = "0.58.0"
          |
          |[lib]
          |crate-type = ['cdylib']
          |
          """.trimMargin(),
        )
      }
    }
  }

  suspend fun generateHostAppKotlinModule() {
    executeIo("generateHostAppKotlinModule") {
      fileSystem.createDirectories(layout.host)
      fileSystem.write(layout.host / "module.yaml") {
        writeUtf8(
          """
          |product:
          |  type: jvm/app
          |
          |settings:
          |  kotlin:
          |    version: 2.4.0
          |  jvm:
          |    jdk:
          |      version: 25
          |    mainClass: dev.wasmo.brevity.integration.HostMainKt
          |
          |repositories:
          |  - mavenLocal
          |
          |dependencies:
          |  - ../api
          |  - com.dylibso.chicory:runtime:1.7.5
          |  - com.squareup.okio:okio:3.16.4
          |  - com.willowtreeapps.assertk:assertk:0.28.1
          |  - dev.wasmo.brevity:brevity-wasi-p1:0-testing
          |  - dev.wasmo.brevity:brevity-wasi-p2:0-testing
          |  - dev.wasmo.brevity:brevity:0-testing
          |
          """.trimMargin(),
        )
      }
    }
  }

  suspend fun compileKotlinGuest() {
    executeCommand(
      "compileKotlinGuest",
      layout.path,
      "kotlin",
      "build",
      "--module",
      "guest",
    )
  }

  suspend fun compileKotlinHost() {
    executeCommand(
      "compileKotlinHost",
      layout.path,
      "kotlin",
      "package",
      "--module",
      "host",
    )
  }

  suspend fun executeKotlinHost(
    name: String,
    hostJar: String,
    guestWasm: String,
  ) {
    executeCommand(
      name,
      layout.path,
      "java",
      "-jar",
      hostJar,
      guestWasm,
    )
  }

  suspend fun compileRustGuest() {
    // Generate .wasm components from Rust sources
    executeCommand(
      "compileRustGuest",
      layout.rust,
      "cargo",
      "build",
      "--target=wasm32-wasip2",
      "--release",
    )

    // Unbundle the .wasm component into a .wasm core module
    executeCommand(
      "compileRustGuest",
      layout.rust,
      "wasm-tools",
      "component",
      "unbundle",
      "--module-dir",
      "target/unbundled/",
      "--output",
      "target/unbundled/component.wasm",
      "./target/wasm32-wasip2/release/brevity_testing.wasm",
    )
  }

  private suspend fun <T> executeIo(
    name: String,
    block: suspend CoroutineScope.() -> T,
  ): T {
    val coroutineName = "${this.name}.$name"
    return withContext(Dispatchers.IO + CoroutineName(coroutineName)) {
      val start = TimeSource.Monotonic.markNow()
      try {
        block()
      } finally {
        val elapsed = TimeSource.Monotonic.markNow() - start
        if (elapsed > 100.milliseconds) {
          println("$coroutineName took $elapsed")
        }
      }
    }
  }

  suspend fun executeCommand(
    name: String,
    directory: Path,
    vararg command: String,
  ) {
    executeIo(name) {
      val process = ProcessBuilder()
        .directory(directory.toFile())
        .command(*command)
        .start()

      val stdout = async {
        Buffer()
          .apply {
            writeAll(process.inputStream.source())
          }
      }

      val stderr = async {
        Buffer()
          .apply {
            writeAll(process.errorStream.source())
          }
      }

      if (process.waitFor() != 0) {
        stdout.join()
        stderr.join()
        throw AssertionError(
          """
          |expected process to return normally
          |
          |stdout:
          |${stdout.await().readUtf8().replace("\n", "\n  ")}
          |
          |stderr:
          |${stderr.await().readUtf8().replace("\n", "\n  ")}
          """.trimMargin(),
        )
      }
    }
  }
}
