package dev.wasmo.brevity.kotlin.generator

import com.squareup.kotlinpoet.BOOLEAN
import com.squareup.kotlinpoet.Documentable
import com.squareup.kotlinpoet.FileSpec
import com.squareup.kotlinpoet.FunSpec
import com.squareup.kotlinpoet.KModifier
import com.squareup.kotlinpoet.ParameterSpec
import com.squareup.kotlinpoet.PropertySpec
import com.squareup.kotlinpoet.TypeSpec
import com.squareup.kotlinpoet.UNIT

class ApiGenerator(
  private val services: List<KtService>,
) {
  fun generate(): List<FileSpec> {
    return services.groupBy { it.type.packageName }
      .map { (`package`, packageServices) ->
        FileSpec.builder(`package`, "Api")
          .addFileComment("Generated by Brevity. Do not edit.")
          .apply {
            for (service in packageServices) {
              val spec = serviceToApi(service) ?: continue
              addType(spec)
            }
          }
          .build()
      }
  }

  private fun <T : Documentable.Builder<*>> T.setDeclaration(
    declaration: KtDeclaration? = null,
  ): T = apply {
    val documentation = declaration?.documentation
    if (documentation != null) {
      addKdoc(documentation.trimIndent())
    }
  }

  private fun recordToApi(value: KtRecord) = TypeSpec.classBuilder(value.type.simpleName)
    .addModifiers(KModifier.DATA)
    .setDeclaration(value)
    .apply {
      val constructorBuilder = FunSpec.constructorBuilder()

      for (field in value.fields) {
        val name = field.name
        val parameter = ParameterSpec.builder(name, field.type.apiType)
          .build()
        constructorBuilder.addParameter(parameter)

        addProperty(
          PropertySpec.builder(name, field.type.apiType)
            .initializer("%N", parameter)
            .setDeclaration(field)
            .build(),
        )
      }

      primaryConstructor(constructorBuilder.build())
    }
    .build()

  private fun resourceToApi(value: KtResource) = TypeSpec.interfaceBuilder(value.type.simpleName)
    .setDeclaration(value)
    .addSuperinterface(Symbols.Brevity.Resource)
    .apply {
      for (function in value.functions) {
        if (!function.isSupported) continue
        addFunction(functionToApi(function))
      }
    }
    .build()

  private fun variantToApi(value: KtVariant) = TypeSpec.interfaceBuilder(value.type.simpleName)
    .addModifiers(KModifier.SEALED)
    .setDeclaration(value)
    .apply {
      for (case in value.cases) {
        val type = case.type
        if (type != null) {
          addType(
            TypeSpec.classBuilder(case.name)
              .addModifiers(KModifier.DATA)
              .addSuperinterface(value.type)
              .primaryConstructor(
                FunSpec.constructorBuilder()
                  .addParameter("value", case.type.apiType)
                  .build(),
              )
              .addProperty(
                PropertySpec.builder("value", case.type.apiType)
                  .initializer("%N", "value")
                  .build(),
              )
              .setDeclaration(case)
              .build(),
          )
        } else {
          addType(
            TypeSpec.objectBuilder(case.name)
              .addModifiers(KModifier.DATA)
              .addSuperinterface(value.type)
              .setDeclaration(case)
              .build(),
          )
        }
      }
    }
    .build()

  private fun enumToApi(value: KtEnum) = TypeSpec.enumBuilder(value.type.simpleName)
    .setDeclaration(value)
    .apply {
      for (case in value.cases) {
        addEnumConstant(
          case.name,
          TypeSpec.anonymousClassBuilder()
            .setDeclaration(case)
            .build(),
        )
      }
    }
    .build()

  private fun typeAliasToApi(value: KtTypeAlias) = TypeSpec.classBuilder(value.type.simpleName)
    .addModifiers(KModifier.VALUE)
    .addAnnotation(JvmInline::class)
    .setDeclaration(value)
    .apply {
      val parameter = ParameterSpec.builder("value", value.target.apiType)
        .build()

      primaryConstructor(
        FunSpec.constructorBuilder()
          .addParameter(parameter)
          .build(),
      )

      addProperty(
        PropertySpec.builder("value", value.target.apiType)
          .initializer("%N", parameter)
          .build(),
      )
    }
    .build()

  private fun flagsToApi(value: KtFlags) = TypeSpec.classBuilder(value.type.simpleName)
    .addModifiers(KModifier.DATA)
    .setDeclaration(value)
    .apply {
      val constructorBuilder = FunSpec.constructorBuilder()

      for (field in value.flags) {
        val parameter = ParameterSpec.builder(field.name, BOOLEAN)
          .build()
        constructorBuilder.addParameter(parameter)
        addProperty(
          PropertySpec.builder(field.name, BOOLEAN)
            .initializer("%N", parameter)
            .setDeclaration(field)
            .build(),
        )
      }

      primaryConstructor(constructorBuilder.build())
    }
    .build()

  private fun functionToApi(value: KtFunction) = FunSpec.builder(value.ktName)
    .addModifiers(KModifier.ABSTRACT)
    .setDeclaration(value)
    .apply {
      for (parameter in value.parameters) {
        addParameter(parameter.name, parameter.type.apiType)
      }
      returns(value.returnType?.apiType ?: UNIT)
    }
    .build()

  private fun serviceToApi(value: KtService): TypeSpec? {
    if (!value.hasInstanceMembers && value.types.isEmpty()) return null

    val builder = when {
      !value.hasInstanceMembers || value is KtWorld -> TypeSpec.objectBuilder(value.type.simpleName)
      else -> TypeSpec.interfaceBuilder(value.type.simpleName)
    }

    value.documentation?.let {
      builder.addKdoc(it)
    }

    for (type in value.types) {
      val typeSpec = when (type) {
        is KtEnum -> enumToApi(type)
        is KtFlags -> flagsToApi(type)
        is KtRecord -> recordToApi(type)
        is KtResource -> resourceToApi(type)
        is KtTypeAlias -> typeAliasToApi(type)
        is KtVariant -> variantToApi(type)
      }

      builder.addType(typeSpec)
    }

    when (value) {
      is KtInterface -> {
        for (function in value.functions) {
          builder.addFunction(functionToApi(function))
        }
      }

      is KtWorld -> {
        if (value.guestApis != null) {
          builder.addType(externalApisToApi(value.guestApis))
        }
        if (value.hostApis != null) {
          builder.addType(externalApisToApi(value.hostApis))
        }
      }
    }

    return builder.build()
  }

  private fun externalApisToApi(value: KtWorld.ExternalApis): TypeSpec {
    return TypeSpec.interfaceBuilder(value.type.simpleName)
      .apply {
        for (item in value.items) {
          when (item) {
            is KtWorld.ExternalApis.InterfaceProperty -> addProperty(item.instanceName, item.type)
            is KtFunction -> addFunction(functionToApi(item))
          }
        }
      }
      .build()
  }
}
