package dev.wasmo.brevity.kotlin.generator

import com.squareup.kotlinpoet.BOOLEAN
import com.squareup.kotlinpoet.Documentable
import com.squareup.kotlinpoet.FileSpec
import com.squareup.kotlinpoet.FunSpec
import com.squareup.kotlinpoet.KModifier
import com.squareup.kotlinpoet.ParameterSpec
import com.squareup.kotlinpoet.PropertySpec
import com.squareup.kotlinpoet.TypeSpec
import com.squareup.kotlinpoet.UNIT
import dev.wasmo.brevity.ir.IrDeclaration
import dev.wasmo.brevity.ir.IrEnum
import dev.wasmo.brevity.ir.IrExternalApi
import dev.wasmo.brevity.ir.IrFlags
import dev.wasmo.brevity.ir.IrFunction
import dev.wasmo.brevity.ir.IrInterface
import dev.wasmo.brevity.ir.IrRecord
import dev.wasmo.brevity.ir.IrResource
import dev.wasmo.brevity.ir.IrTypeAlias
import dev.wasmo.brevity.ir.IrVariant
import dev.wasmo.brevity.ir.IrWitPackage
import dev.wasmo.brevity.ir.IrWorld

class ApiGenerator(
  private val packages: List<IrWitPackage>,
) {
  fun generate(): List<FileSpec> {
    return packages.map { witPackage ->
      FileSpec.builder(witPackage.packageName.toKotlin().name, "Api")
        .addFileComment("Generated by Brevity. Do not edit.")
        .apply {
          for (service in witPackage.services) {
            val spec = serviceToApi(service) ?: continue
            addType(spec)
          }
        }
        .build()
    }
  }

  private fun <T : Documentable.Builder<*>> T.setDeclaration(
    declaration: IrDeclaration? = null,
  ): T = apply {
    val documentation = declaration?.documentation
    if (documentation != null) {
      addKdoc(documentation.content.trimIndent())
    }
  }

  private fun recordToApi(value: IrRecord) = TypeSpec.classBuilder(value.type.kotlinApi)
    .addModifiers(KModifier.DATA)
    .setDeclaration(value)
    .apply {
      val constructorBuilder = FunSpec.constructorBuilder()

      for (field in value.fields) {
        val name = field.kotlinName
        val parameter = ParameterSpec.builder(name, field.type.kotlinApi)
          .build()
        constructorBuilder.addParameter(parameter)

        addProperty(
          PropertySpec.builder(name, field.type.kotlinApi)
            .initializer("%N", parameter)
            .setDeclaration(field)
            .build(),
        )
      }

      primaryConstructor(constructorBuilder.build())
    }
    .build()

  private fun resourceToApi(value: IrResource) = TypeSpec.interfaceBuilder(value.type.kotlinApi)
    .setDeclaration(value)
    .addSuperinterface(Symbols.Brevity.Resource)
    .apply {
      for (function in value.functions) {
        if (!function.isSupported) continue
        addFunction(functionToApi(function))
      }
    }
    .build()

  private fun variantToApi(value: IrVariant) = TypeSpec.interfaceBuilder(value.type.kotlinApi)
    .addModifiers(KModifier.SEALED)
    .setDeclaration(value)
    .apply {
      for (case in value.cases) {
        val type = case.type
        if (type != null) {
          addType(
            TypeSpec.classBuilder(case.kotlinName)
              .addModifiers(KModifier.DATA)
              .addSuperinterface(value.type.kotlinApi)
              .primaryConstructor(
                FunSpec.constructorBuilder()
                  .addParameter("value", type.kotlinApi)
                  .build(),
              )
              .addProperty(
                PropertySpec.builder("value", type.kotlinApi)
                  .initializer("%N", "value")
                  .build(),
              )
              .setDeclaration(case)
              .build(),
          )
        } else {
          addType(
            TypeSpec.objectBuilder(case.kotlinName)
              .addModifiers(KModifier.DATA)
              .addSuperinterface(value.type.kotlinApi)
              .setDeclaration(case)
              .build(),
          )
        }
      }
    }
    .build()

  private fun enumToApi(value: IrEnum) = TypeSpec.enumBuilder(value.type.kotlinApi)
    .setDeclaration(value)
    .apply {
      for (case in value.cases) {
        addEnumConstant(
          case.kotlinName,
          TypeSpec.anonymousClassBuilder()
            .setDeclaration(case)
            .build(),
        )
      }
    }
    .build()

  private fun typeAliasToApi(value: IrTypeAlias) = TypeSpec.classBuilder(value.type.kotlinApi)
    .addModifiers(KModifier.VALUE)
    .addAnnotation(JvmInline::class)
    .setDeclaration(value)
    .apply {
      val parameter = ParameterSpec.builder("value", value.target.kotlinApi)
        .build()

      primaryConstructor(
        FunSpec.constructorBuilder()
          .addParameter(parameter)
          .build(),
      )

      addProperty(
        PropertySpec.builder("value", value.target.kotlinApi)
          .initializer("%N", parameter)
          .build(),
      )
    }
    .build()

  private fun flagsToApi(value: IrFlags) = TypeSpec.classBuilder(value.type.kotlinApi)
    .addModifiers(KModifier.DATA)
    .setDeclaration(value)
    .apply {
      val constructorBuilder = FunSpec.constructorBuilder()

      for (field in value.flags) {
        val parameter = ParameterSpec.builder(field.kotlinName, BOOLEAN)
          .build()
        constructorBuilder.addParameter(parameter)
        addProperty(
          PropertySpec.builder(field.kotlinName, BOOLEAN)
            .initializer("%N", parameter)
            .setDeclaration(field)
            .build(),
        )
      }

      primaryConstructor(constructorBuilder.build())
    }
    .build()

  private fun functionToApi(value: IrFunction) = FunSpec.builder(value.kotlinName)
    .addModifiers(KModifier.ABSTRACT)
    .setDeclaration(value)
    .apply {
      for (parameter in value.parameters) {
        addParameter(parameter.kotlinName, parameter.type.kotlinApi)
      }
      returns(value.returnType?.kotlinApi ?: UNIT)
    }
    .build()

  private fun serviceToApi(value: IrWitPackage.Service): TypeSpec? {
    if (!value.hasInstanceMembers && value.types.isEmpty()) return null

    val typeName = value.serviceName.kotlinApi

    val builder = when {
      !value.hasInstanceMembers || value is IrWorld -> TypeSpec.objectBuilder(typeName)
      else -> TypeSpec.interfaceBuilder(typeName)
    }

    value.documentation?.let {
      builder.addKdoc(it.content.trimIndent())
    }

    for (type in value.types) {
      val typeSpec = when (type) {
        is IrEnum -> enumToApi(type)
        is IrFlags -> flagsToApi(type)
        is IrRecord -> recordToApi(type)
        is IrResource -> resourceToApi(type)
        is IrTypeAlias -> typeAliasToApi(type)
        is IrVariant -> variantToApi(type)
      }

      builder.addType(typeSpec)
    }

    when (value) {
      is IrInterface -> {
        for (function in value.functions) {
          builder.addFunction(functionToApi(function))
        }
      }

      is IrWorld -> {
        val guestApis = value.guestApis
        if (guestApis != null) {
          builder.addType(externalApisToApi(guestApis))
        }
        val hostApis = value.hostApis
        if (hostApis != null) {
          builder.addType(externalApisToApi(hostApis))
        }
      }
    }

    return builder.build()
  }

  private fun externalApisToApi(value: ExternalApis): TypeSpec {
    return TypeSpec.interfaceBuilder(value.type.simpleName)
      .apply {
        for (item in value.items) {
          when (item) {
            is IrExternalApi -> addProperty(item.instanceName, item.serviceName.kotlinApi)
            is IrFunction -> addFunction(functionToApi(item))
          }
        }
      }
      .build()
  }
}
