package dev.wasmo.brevity.kotlin.generator

import com.squareup.kotlinpoet.CodeBlock
import com.squareup.kotlinpoet.FileSpec
import dev.wasmo.brevity.ir.IrDeclaration

fun FileSpec.Builder.addBrevityComment(declaration: IrDeclaration) = apply {
  addFileComment("Generated by Brevity. Do not edit.")
  addFileComment("\n  ${declaration.location.path}")
}

operator fun CodeBlock.plus(offset: Int): CodeBlock {
  return when {
    offset != 0 -> CodeBlock.of("%L + %L", this, offset)
    else -> this
  }
}
