package dev.wasmo.brevity.kotlin.generator

import com.squareup.kotlinpoet.FileSpec
import dev.wasmo.brevity.ir.IrDeclaration

fun FileSpec.Builder.addBrevityComment(declarations: Iterable<IrDeclaration>) = apply {
  addFileComment("Generated by Brevity. Do not edit.")
  val sourcePaths = declarations.map { it.location.path }
    .toSortedSet()
  for (sourcePath in sourcePaths) {
    addFileComment("\n  $sourcePath")
  }
}
