package dev.wasmo.brevity.kotlin.generator


import com.squareup.kotlinpoet.CodeBlock
import com.squareup.kotlinpoet.FileSpec
import com.squareup.kotlinpoet.FunSpec
import com.squareup.kotlinpoet.INT
import com.squareup.kotlinpoet.KModifier
import com.squareup.kotlinpoet.PropertySpec
import com.squareup.kotlinpoet.TypeSpec
import dev.wasmo.brevity.kotlin.generator.GuestBridgeBuilder.Receiver

class GuestGenerator(
  private val declarationIndex: DeclarationIndex,
  private val worldIndex: WorldIndex,
  private val services: List<KtService>,
) {
  private val bridgeBuilder = GuestBridgeBuilder(declarationIndex)

  fun generate(): List<FileSpec> {
    val bridges = worldIndex.map.values.groupBy { it.declaration.type.packageName }
      .mapNotNull { (`package`, entries) ->
        FileSpec.builder(`package`, "GuestTypes")
          .addFileComment("Generated by Brevity. Do not edit.")
          .apply {
            for (entry in entries) {
              addCodec(entry)
            }
          }
          .build()
          .takeIf { it.members.isNotEmpty() }
      }

    val services = services.groupBy { it.type.packageName }
      .mapNotNull { (`package`, packageServices) ->
        FileSpec.builder(`package`, "GuestServices")
          .addFileComment("Generated by Brevity. Do not edit.")
          .apply {
            for (service in packageServices) {
              generateService(service)

              if (service is KtWorld) {
                addExternalFunctions(service)
              }
            }
          }
          .build()
          .takeIf { it.members.isNotEmpty() }
      }

    return bridges + services
  }

  private fun FileSpec.Builder.generateService(value: KtService) {
    if (value is KtWorld) {
      if (value.guestApis != null) {
        val service = value.guestApis
        addProperty(
          PropertySpec.builder("${service.instanceName}_", service.type)
            .addModifiers(KModifier.PRIVATE, KModifier.LATEINIT)
            .mutable(true)
            .build(),
        )
        addProperty(
          PropertySpec.builder(service.instanceName, service.type)
            .receiver(value.type)
            .mutable(true)
            .getter(
              FunSpec.getterBuilder()
                .addCode("return %N", "${service.instanceName}_")
                .build(),
            )
            .setter(
              FunSpec.setterBuilder()
                .addParameter("value", service.type)
                .addCode("%N = %N", "${service.instanceName}_", "value")
                .build(),
            )
            .build(),
        )
      }
    }
  }

  private fun FileSpec.Builder.addCodec(entry: WorldIndex.Entry) {
    when (entry.declaration) {
      is KtResource -> {
        addResource(
          value = entry.declaration,
          host = entry.host,
          guest = entry.guest,
        )
      }

      else -> {} // TODO
    }
  }

  private fun FileSpec.Builder.addResource(
    value: KtResource,
    host: Boolean,
    guest: Boolean,
  ) {
    val receiver = Receiver.Id(
      type = KtTypeName.Simple(value.type, INT),
    )

    if (guest) {
      for (function in value.functions) {
        if (!function.isSupported) continue // TODO
        addFunction(bridgeBuilder.wasmExportFunction(receiver, function))
      }
    }

    if (host) {
      val handleBuilder = TypeSpec.classBuilder(value.handleName)
        .addModifiers(KModifier.INTERNAL)
        .addSuperinterface(value.type)
        .primaryConstructor(
          FunSpec.constructorBuilder()
            .addParameter("id", INT)
            .build(),
        )
        .addProperty(
          PropertySpec.builder("id", INT)
            .addModifiers(KModifier.PRIVATE)
            .initializer("id")
            .build(),
        )

      for (function in value.functions) {
        if (!function.isSupported) continue // TODO
        handleBuilder.addFunction(bridgeBuilder.callHostFunction(receiver, function))
        addFunction(bridgeBuilder.wasmImportFunction(receiver, function))
      }

      addType(handleBuilder.build())
    }
  }

  /**
   * Generate top-level `@WasmExport`-annotated functions for all exported functions in [value],
   * and functions recursively held by [value].
   */
  private fun FileSpec.Builder.addExternalFunctions(value: KtWorld) {
    // The object to dereference that defines the true implementation. This is either the guest
    // interface or one of its members.
    if (value.guestApis == null) return

    for (item in value.guestApis.items) {
      when (item) {
        is KtFunction -> {
          val receiver = Receiver.Global(
            CodeBlock.of("%N_", value.guestApis.instanceName),
          )
          addFunction(
            bridgeBuilder.wasmExportFunction(
              receiver = receiver,
              value = item,
            ),
          )
        }

        is KtWorld.ExternalApis.InterfaceProperty -> {
          val ktInterface = declarationIndex[item.type] as KtInterface
          val receiver = Receiver.Global(
            CodeBlock.of("%N_.%N", value.guestApis.instanceName, item.instanceName),
          )
          for (function in ktInterface.functions) {
            addFunction(
              bridgeBuilder.wasmExportFunction(
                receiver = receiver,
                value = function,
              ),
            )
          }
        }
      }
    }
  }
}
