package dev.wasmo.brevity.kotlin.generator


import com.squareup.kotlinpoet.AnnotationSpec
import com.squareup.kotlinpoet.CodeBlock
import com.squareup.kotlinpoet.FileSpec
import com.squareup.kotlinpoet.FunSpec
import com.squareup.kotlinpoet.INT
import com.squareup.kotlinpoet.KModifier
import com.squareup.kotlinpoet.ParameterSpec
import com.squareup.kotlinpoet.PropertySpec
import dev.wasmo.brevity.Annotation

class GuestGenerator(
  private val index: WorldIndex,
  private val services: List<KtService>,
) {
  fun generate(): List<FileSpec> {
    return services.groupBy { it.type.packageName }
      .mapNotNull { (`package`, packageServices) ->
        FileSpec.builder(`package`, "Guest")
          .addFileComment("Generated by Brevity. Do not edit.")
          .apply {
            for (service in packageServices) {
              if (service.functions.isNotEmpty() || service.types.isNotEmpty()) {
                generateService(service)
              }

              if (service is KtWorld) {
                addWasmExportFunctions(
                  enclosing = null,
                  value = service,
                )
                for (entry in index.map.values) {
                  addCodec(entry)
                }
              }
            }
          }
          .build()
          .takeIf { it.members.isNotEmpty() }
      }
  }

  private fun FileSpec.Builder.generateService(
    value: KtService,
  ) {
    for (service in value.services) {
      if (value.type == service.type.enclosingClassName()) {
        generateService(
          value = service,
        )
      }

      if (service.kind == KtService.Kind.Guest) {
        addProperty(
          PropertySpec.builder("${service.instanceName}_", service.type)
            .addModifiers(KModifier.PRIVATE, KModifier.LATEINIT)
            .mutable(true)
            .build(),
        )
        addProperty(
          PropertySpec.builder(service.instanceName, service.type)
            .receiver(value.type)
            .mutable(true)
            .getter(
              FunSpec.getterBuilder()
                .addCode("return %N", "${service.instanceName}_")
                .build(),
            )
            .setter(
              FunSpec.setterBuilder()
                .addParameter("value", service.type)
                .addCode("%N = %N", "${service.instanceName}_", "value")
                .build(),
            )
            .build(),
        )
      }
    }
  }

  private fun FileSpec.Builder.addCodec(entry: WorldIndex.Entry) {
    if (!entry.guest) return // TODO: add decoder for these.

    when (entry.declaration) {
      is KtResource -> {
        for (function in entry.declaration.functions) {
          addWasmExportFunction(
            receiver = Receiver.Id(
              name = "self",
              type = KtTypeName.Simple(entry.declaration.type, INT),
            ),
            value = function,
          )
        }
      }

      else -> {} // TODO
    }
  }

  /**
   * Generate top-level `@WasmExport`-annotated functions for all exported functions in [value],
   * and functions recursively held by [value].
   */
  private fun FileSpec.Builder.addWasmExportFunctions(
    enclosing: CodeBlock?,
    value: KtService,
  ) {
    // The object to dereference that defines the true implementation. This is either the guest
    // interface or one of its members.
    val instance = when (value.kind) {
      KtService.Kind.Guest -> Receiver.Global(CodeBlock.of("%N_", value.instanceName))
      KtService.Kind.Interface if enclosing != null -> Receiver.Global(
        CodeBlock.of("%L.%N", enclosing, value.instanceName),
      )

      else -> null
    }

    if (instance != null && index[value.type]?.guest == true) {
      for (function in value.functions) {
        addWasmExportFunction(
          receiver = instance,
          value = function,
        )
      }
    }

    for (service in value.services) {
      addWasmExportFunctions(
        enclosing = instance?.codeBlock,
        value = service,
      )
    }
  }

  private fun FileSpec.Builder.addWasmExportFunction(
    receiver: Receiver,
    value: KtFunction,
  ) {
    when (value.name.annotation) {
      Annotation.Constructor, Annotation.Static -> return // TODO.
      else -> {}
    }

    addFunction(
      FunSpec.builder(value.name.fullyQualifiedKotlinName)
        .addModifiers(KModifier.PRIVATE)
        .addAnnotation(
          AnnotationSpec.builder(Symbols.KotlinWasm.WasmExport)
            .addMember("%S", value.name)
            .build(),
        )
        .apply {
          if (value.returnType != null) {
            addCode("val %N = ", "result")
            returns(value.returnType.abiType)
          }

          if (receiver is Receiver.Id) {
            addParameter(receiver.name, receiver.type.abiType)
          }

          addCode("%L", receiver.codeBlock)

          val guestBridge = CodeBlock.of("%T", Symbols.Brevity.GuestBridge)
          addCode(".%N(", value.ktName)
          for ((index, parameter) in value.parameters.withIndex()) {
            if (index > 0) addCode(", ")
            addParameter(ParameterSpec.builder(parameter.name, parameter.type.abiType).build())
            addCode(guestAbiToApi(guestBridge, parameter.type, CodeBlock.of("%N", parameter.name)))
          }
          addCode(")\n")

          if (value.returnType != null) {
            addCode(
              "return %L\n",
              guestApiToAbi(guestBridge, value.returnType, CodeBlock.of("%N", "result")),
            )
          }
        }
        .build(),
    )
  }

  internal sealed interface Receiver {
    val codeBlock: CodeBlock

    data class Global(
      override val codeBlock: CodeBlock,
    ) : Receiver

    data class Id(
      val name: String,
      val type: KtTypeName,
    ) : Receiver {
      override val codeBlock: CodeBlock
        get() = CodeBlock.of(
          "(%N as %T)",
          name,
          type.apiType,
        )
    }
  }
}
