package dev.wasmo.brevity.kotlin.generator

import com.squareup.kotlinpoet.ClassName
import com.squareup.kotlinpoet.CodeBlock
import com.squareup.kotlinpoet.FileSpec
import com.squareup.kotlinpoet.FunSpec
import com.squareup.kotlinpoet.KModifier
import com.squareup.kotlinpoet.LambdaTypeName
import com.squareup.kotlinpoet.ParameterSpec
import com.squareup.kotlinpoet.ParameterizedTypeName.Companion.parameterizedBy
import com.squareup.kotlinpoet.PropertySpec
import com.squareup.kotlinpoet.TypeSpec
import com.squareup.kotlinpoet.UNIT
import com.squareup.kotlinpoet.buildCodeBlock
import dev.wasmo.brevity.Annotation

class HostGenerator {
  fun generate(services: List<KtService>): List<FileSpec> {
    return services.groupBy { it.type.packageName }
      .map { (`package`, packageServices) ->
        FileSpec.builder(`package`, "Host")
          .addFileComment("Generated by Brevity. Do not edit.")
          .apply {
            for (service in packageServices) {
              val factoryFunction = worldFactoryFunction(service)
              if (factoryFunction != null) {
                addFunction(factoryFunction)
              }

              val typeSpec = serviceToHost(service) ?: continue
              addType(typeSpec)
            }
          }
          .build()
      }
  }

  private fun worldFactoryFunction(value: KtService): FunSpec? {
    if (value.kind != KtService.Kind.World) return null

    // The implemented World interface uses the interface types; everything else uses the
    // implementation types.
    val onlyGuest = value.onlyGuestOrNull
    val onlyHost = value.onlyHostOrNull
    val worldType = Symbols.Brevity.World.parameterizedBy(
      onlyHost?.type ?: UNIT,
      onlyGuest?.type ?: UNIT,
    )

    val hostFactory = ParameterSpec.builder(
      "hostFactory",
      LambdaTypeName.get(
        parameters = listOf(ParameterSpec.unnamed(onlyGuest?.type ?: UNIT)),
        returnType = onlyHost?.type ?: UNIT,
      ),
    ).build()

    return FunSpec.builder("World")
      .receiver(value.type)
      .addParameter(hostFactory)
      .returns(worldType)
      .apply {
        addStatement("val %N = %T()", "bridge", Symbols.Brevity.HostBridge)

        if (onlyGuest != null) {
          addStatement("val %N = %T(%N)", "guest", onlyGuest.bridgeType, "bridge")
        } else {
          addStatement("val %N = %T", "guest", UNIT)
        }

        addStatement("val %N = %N(%N)", "host", "hostFactory", "guest")

        addStatement(
          "return %T(%N, %N, %N)",
          value.bridgeType,
          "bridge",
          "guest",
          "host",
        )
      }
      .build()
  }

  private fun functionToHost(value: KtFunction) = FunSpec.builder(value.ktName)
    .addModifiers(KModifier.OVERRIDE)
    .apply {
      if (value.returnType != null) {
        addCode("val %N = ", "result")
      }
      addCode("%N.apply(⇥\n", value.ktName)

      for (parameter in value.parameters) {
        addParameter(parameter.name, parameter.type.apiType)
        addCode(
          hostApiToAbi(
            bridge = CodeBlock.of("%N", "bridge"),
            type = parameter.type,
            apiValue = CodeBlock.of("%N", parameter.name),
          ),
        )
        addCode(",\n")
      }
      addCode("⇤)\n")

      if (value.returnType != null) {
        addCode(
          "return %L",
          hostAbiToApi(
            bridge = CodeBlock.of("%N", "bridge"),
            type = value.returnType,
            abiValue = CodeBlock.of("result[%L]", 0),
          ),
        )
        returns(value.returnType.apiType)
      }
    }
    .build()

  private fun serviceToHost(value: KtService): TypeSpec? {
    if (value.functions.isEmpty() && value.services.isEmpty()) return null

    val builder = TypeSpec.classBuilder(value.bridgeType)
      .addModifiers(KModifier.INTERNAL)

    if (value.kind != KtService.Kind.World) {
      builder.addSuperinterface(value.type)
    }

    val constructor = FunSpec.constructorBuilder()

    constructor.addParameter("bridge", Symbols.Brevity.HostBridge)
    builder.addProperty(
      PropertySpec.builder("bridge", Symbols.Brevity.HostBridge)
        .addModifiers(KModifier.PRIVATE)
        .initializer("bridge")
        .build(),
    )

    if (value.kind == KtService.Kind.World) {
      val onlyGuest = value.onlyGuestOrNull
      val onlyGuestType = onlyGuest?.bridgeType ?: UNIT
      val onlyHost = value.onlyHostOrNull
      val onlyHostType = onlyHost?.type ?: UNIT

      builder.addSuperinterface(
        Symbols.Brevity.World.parameterizedBy(
          onlyHost?.type ?: UNIT,
          onlyGuest?.type ?: UNIT,
        ),
      )

      constructor.addParameter("guest", onlyGuestType)
      builder.addProperty(
        PropertySpec.builder("guest", onlyGuestType)
          .addModifiers(KModifier.OVERRIDE)
          .initializer("guest")
          .build(),
      )

      constructor.addParameter("host", onlyHostType)
      builder.addProperty(
        PropertySpec.builder("host", onlyHostType)
          .addModifiers(KModifier.OVERRIDE)
          .initializer("host")
          .build(),
      )

      builder.addFunction(
        FunSpec.builder("initExports")
          .addModifiers(KModifier.OVERRIDE)
          .addParameter("instance", Symbols.ChicoryRuntime.Instance)
          .apply {
            if (onlyGuest != null) {
              initExports(
                bridge = CodeBlock.of("%N", "guest"),
                instance = CodeBlock.of("%N", "instance"),
                value = onlyGuest,
              )
            }
          }
          .build(),
      )

      builder.addFunction(
        FunSpec.builder("initImports")
          .addModifiers(KModifier.OVERRIDE)
          .addParameter("store", Symbols.ChicoryRuntime.Store)
          .apply {
            if (onlyHost != null) {
              initImports(
                bridge = CodeBlock.of("%N", "guest"),
                store = CodeBlock.of("%N", "store"),
                self = CodeBlock.of("%N", "host"),
                value = onlyHost,
              )
            }
          }
          .build(),
      )
    }

    for (service in value.services) {
      if (value.kind != KtService.Kind.World) {
        builder.addProperty(
          PropertySpec.builder(service.instanceName, service.bridgeType)
            .addModifiers(KModifier.OVERRIDE)
            .initializer("%T(%N)", service.bridgeType, "bridge")
            .build(),
        )
      }

      if (value.type == service.type.enclosingClassName()) {
        val typeSpec = serviceToHost(service) ?: continue
        builder.addType(typeSpec)
      }
    }

    for (function in value.functions) {
      builder.addFunction(functionToHost(function))
      builder.addProperty(
        PropertySpec.builder(function.ktName, Symbols.ChicoryRuntime.ExportFunction)
          .addModifiers(KModifier.INTERNAL, KModifier.LATEINIT)
          .mutable(true)
          .build(),
      )
    }

    builder.primaryConstructor(constructor.build())

    return builder.build()
  }

  private fun FunSpec.Builder.initExports(
    bridge: CodeBlock,
    instance: CodeBlock,
    value: KtService,
  ) {
    for (function in value.functions) {
      addStatement(
        "%L.%N = %L.export(%S)",
        bridge,
        function.ktName,
        instance,
        function.name,
      )
    }
    for (service in value.services) {
      initExports(
        CodeBlock.of("%L.%N", bridge, service.instanceName),
        instance,
        service,
      )
    }
  }

  private fun FunSpec.Builder.initImports(
    bridge: CodeBlock,
    store: CodeBlock,
    self: CodeBlock,
    value: KtService,
  ) {
    for (function in value.functions) {
      addHostFunction(bridge, store, self, function)
    }
    for (service in value.services) {
      initImports(
        bridge = CodeBlock.of("%L.%N", bridge, service.instanceName),
        store = store,
        self = CodeBlock.of("%L.%N", self, service.instanceName),
        value = service,
      )
    }
  }

  private fun FunSpec.Builder.addHostFunction(
    bridge: CodeBlock,
    store: CodeBlock,
    self: CodeBlock,
    value: KtFunction,
  ) {
    when (value.name.annotation) {
      Annotation.Static, Annotation.Constructor -> return // TODO
      else -> {}
    }

    val block = CodeBlock.builder()
    var argIndex = 0

    val abiParameterTypes = buildCodeBlock {
      when (value.name.annotation) {
        Annotation.Method, Annotation.ResourceDrop -> add("%T.I32", Symbols.ChicoryRuntime.ValType)
        else -> {}
      }
      for (parameter in value.parameters) {
        if (isNotEmpty()) add(", ")
        add(parameter.type.toValType())
      }
    }

    block.addStatement("val %N = %L", "self", self)
    when (value.name.annotation) {
      Annotation.Method, Annotation.ResourceDrop -> argIndex++
      else -> {}
    }

    if (value.returnType != null) {
      block.add("val %N = ", "result")
    }
    block.add("%N.%N(⇥\n", "self", value.ktName)
    for (parameter in value.parameters) {
      block.add(
        "%L,\n",
        hostAbiToApi(
          bridge = bridge,
          type = parameter.type,
          abiValue = CodeBlock.of("%N[%L]", "args", argIndex++),
        ),
      )
    }
    block.add("⇤)\n")
    if (value.returnType != null) {
      block.add(
        "return@%T longArrayOf(%L)",
        Symbols.ChicoryRuntime.WasmFunctionHandle,
        hostApiToAbi(bridge, value.returnType, CodeBlock.of("%N", "result")),
      )
    } else {
      block.add(
        "return@%T longArrayOf()",
        Symbols.ChicoryRuntime.WasmFunctionHandle,
      )
    }

    addCode(
      """
      |%L.addFunction(
      |  %T(
      |    %L,
      |    %S,
      |    %T.of(
      |      listOf(%L),
      |      listOf(%L),
      |    ),
      |    %T { instance, args ->
      |      ⇥⇥⇥%L⇤⇤⇤
      |    },
      |  )
      |)
      |
      """.trimMargin(),
      store,
      Symbols.ChicoryRuntime.HostFunction,
      value.name.moduleName?.let { CodeBlock.of("%S", it) } ?: CodeBlock.of("null"),
      value.name.abiName,
      Symbols.ChicoryRuntime.FunctionType,
      abiParameterTypes,
      value.returnType?.toValType() ?: CodeBlock.of(""),
      Symbols.ChicoryRuntime.WasmFunctionHandle,
      block.build(),
    )
  }
}

private val KtService.onlyGuestOrNull: KtService?
  get() = services.singleOrNull { it.kind == KtService.Kind.Guest }

private val KtService.onlyHostOrNull: KtService?
  get() = services.singleOrNull { it.kind == KtService.Kind.Host }

private val KtService.bridgeType: ClassName
  get() = ClassName(
    packageName = type.packageName,
    simpleNames = type.simpleNames.map { "Bridge${it}" },
  )

private fun KtTypeName.toValType() =
  CodeBlock.of("%T.I32", Symbols.ChicoryRuntime.ValType)
