package dev.wasmo.brevity.kotlin.generator

import com.squareup.kotlinpoet.ClassName
import com.squareup.kotlinpoet.CodeBlock
import com.squareup.kotlinpoet.FileSpec
import com.squareup.kotlinpoet.FunSpec
import com.squareup.kotlinpoet.KModifier
import com.squareup.kotlinpoet.LambdaTypeName
import com.squareup.kotlinpoet.ParameterSpec
import com.squareup.kotlinpoet.ParameterizedTypeName.Companion.parameterizedBy
import com.squareup.kotlinpoet.PropertySpec
import com.squareup.kotlinpoet.TypeSpec
import com.squareup.kotlinpoet.UNIT
import com.squareup.kotlinpoet.buildCodeBlock

class HostGenerator(
  private val index: WorldIndex,
  private val services: List<KtNewService>,
) {
  fun generate(): List<FileSpec> {
    return services.groupBy { it.type.packageName }
      .mapNotNull { (`package`, packageServices) ->
        FileSpec.builder(`package`, "Host")
          .addFileComment("Generated by Brevity. Do not edit.")
          .apply {
            for (service in packageServices) {
              if (service is KtWorld) {
                val worldFactoryFunction = worldFactoryFunction(service)
                if (worldFactoryFunction != null) {
                  addFunction(worldFactoryFunction)
                }
              }

              val typeSpec = serviceToHost(service) ?: continue
              addType(typeSpec)
            }
          }
          .build()
          .takeIf { it.members.isNotEmpty() }
      }
  }

  private fun worldFactoryFunction(value: KtWorld): FunSpec? {
    if (value.guestApis == null && value.hostApis == null) return null

    // The implemented World interface uses the interface types; everything else uses the
    // implementation types.
    val worldType = Symbols.Brevity.World.parameterizedBy(
      value.hostApis?.type ?: UNIT,
      value.guestApis?.type ?: UNIT,
    )

    val hostFactory = ParameterSpec.builder(
      "hostFactory",
      LambdaTypeName.get(
        parameters = listOf(ParameterSpec.unnamed(value.guestApis?.type ?: UNIT)),
        returnType = value.hostApis?.type ?: UNIT,
      ),
    ).build()

    return FunSpec.builder("World")
      .receiver(value.type)
      .addParameter(hostFactory)
      .returns(worldType)
      .apply {
        addStatement("val %N = %T()", "bridge", Symbols.Brevity.HostBridge)

        if (value.guestApis != null) {
          addStatement("val %N = %T(%N)", "guest", value.guestApis.bridgeType, "bridge")
        } else {
          addStatement("val %N = %T", "guest", UNIT)
        }

        addStatement("val %N = %N(%N)", "host", "hostFactory", "guest")

        addStatement(
          "return %T(%N, %N, %N)",
          value.bridgeType,
          "bridge",
          "guest",
          "host",
        )
      }
      .build()
  }

  private fun functionToHost(value: KtFunction) = FunSpec.builder(value.ktName)
    .addModifiers(KModifier.OVERRIDE)
    .apply {
      if (value.returnType != null) {
        addCode("val %N = ", "result")
      }
      addCode("%N.apply(⇥\n", value.ktName)

      for (parameter in value.parameters) {
        addParameter(parameter.name, parameter.type.apiType)
        addCode(
          hostApiToAbi(
            bridge = CodeBlock.of("%N", "bridge"),
            type = parameter.type,
            apiValue = CodeBlock.of("%N", parameter.name),
          ),
        )
        addCode(",\n")
      }
      addCode("⇤)\n")

      if (value.returnType != null) {
        addCode(
          "return %L",
          hostAbiToApi(
            bridge = CodeBlock.of("%N", "bridge"),
            type = value.returnType,
            abiValue = CodeBlock.of("result[%L]", 0),
          ),
        )
        returns(value.returnType.apiType)
      }
    }
    .build()

  private fun serviceToHost(value: KtNewService): TypeSpec? {
    if (!value.hasInstanceMembers) return null

    val builder = TypeSpec.classBuilder(value.bridgeType)
      .addModifiers(KModifier.INTERNAL)

    if (value !is KtWorld) {
      builder.addSuperinterface(value.type)
    }

    val constructor = FunSpec.constructorBuilder()

    constructor.addParameter("bridge", Symbols.Brevity.HostBridge)
    builder.addProperty(
      PropertySpec.builder("bridge", Symbols.Brevity.HostBridge)
        .addModifiers(KModifier.PRIVATE)
        .initializer("bridge")
        .build(),
    )

    if (value is KtWorld) {
      val guestType = value.guestApis?.bridgeType ?: UNIT
      val hostType = value.hostApis?.type ?: UNIT

      builder.addSuperinterface(
        Symbols.Brevity.World.parameterizedBy(
          value.hostApis?.type ?: UNIT,
          value.guestApis?.type ?: UNIT,
        ),
      )

      constructor.addParameter("guest", guestType)
      builder.addProperty(
        PropertySpec.builder("guest", guestType)
          .addModifiers(KModifier.OVERRIDE)
          .initializer("guest")
          .build(),
      )

      constructor.addParameter("host", hostType)
      builder.addProperty(
        PropertySpec.builder("host", hostType)
          .addModifiers(KModifier.OVERRIDE)
          .initializer("host")
          .build(),
      )

      builder.addFunction(
        FunSpec.builder("initExports")
          .addModifiers(KModifier.OVERRIDE)
          .addParameter("instance", Symbols.ChicoryRuntime.Instance)
          .apply {
            if (value.guestApis != null) {
              initExports(
                guest = CodeBlock.of("%N", "guest"),
                instance = CodeBlock.of("%N", "instance"),
                value = value.guestApis,
              )
            }
          }
          .build(),
      )

      builder.addFunction(
        FunSpec.builder("initImports")
          .addModifiers(KModifier.OVERRIDE)
          .addParameter("store", Symbols.ChicoryRuntime.Store)
          .apply {
            if (value.hostApis != null) {
              val receiver = Receiver.Instance(
                codeBlock = CodeBlock.of("%N", "host"),
              )
              initImports(
                bridge = CodeBlock.of("%N", "bridge"),
                store = CodeBlock.of("%N", "store"),
                receiver = receiver,
                value = value.hostApis,
              )
            }
            for (entry in index.map.values) {
              initImports(
                bridge = CodeBlock.of("%N", "bridge"),
                store = CodeBlock.of("%N", "store"),
                value = entry,
              )
            }
          }
          .build(),
      )
    }

    when (value) {
      is KtWorld -> {
        if (value.guestApis != null) {
          builder.addExternalApis(value.guestApis)
        }
        if (value.hostApis != null) {
          builder.addExternalApis(value.hostApis)
        }
      }

      is KtInterface -> {
        for (item in value.functions) {
          builder.addFunction(functionToHost(item))
          builder.addProperty(
            PropertySpec.builder(item.ktName, Symbols.ChicoryRuntime.ExportFunction)
              .addModifiers(KModifier.INTERNAL, KModifier.LATEINIT)
              .mutable(true)
              .build(),
          )
        }
      }
    }

    builder.primaryConstructor(constructor.build())

    return builder.build()
  }

  private fun TypeSpec.Builder.addExternalApis(externalApis: KtWorld.ExternalApis) {
    addType(
      TypeSpec.classBuilder(externalApis.bridgeType)
        .addModifiers(KModifier.INTERNAL)
        .addSuperinterface(externalApis.type)
        .primaryConstructor(
          FunSpec.constructorBuilder()
            .addParameter("bridge", Symbols.Brevity.HostBridge)
            .build(),
        )
        .addProperty(
          PropertySpec.builder("bridge", Symbols.Brevity.HostBridge)
            .addModifiers(KModifier.PRIVATE)
            .initializer("bridge")
            .build(),
        )
        .apply {
          for (item in externalApis.items) {
            addExternalApisItem(externalApis, item)
          }
        }
        .build(),
    )
  }

  private fun TypeSpec.Builder.addExternalApisItem(
    externalApis: KtWorld.ExternalApis,
    item: KtWorld.ExternalApis.Item,
  ) {
    when (item) {
      is KtWorld.ExternalApis.InterfaceProperty -> {
        addProperty(
          PropertySpec.builder(item.instanceName, item.bridgeType)
            .addModifiers(KModifier.OVERRIDE)
            .initializer("%T(%N)", item.bridgeType, "bridge")
            .build(),
        )
      }

      is KtFunction -> {
        addFunction(functionToHost(item))
        addProperty(
          PropertySpec.builder(item.ktName, Symbols.ChicoryRuntime.ExportFunction)
            .addModifiers(KModifier.INTERNAL, KModifier.LATEINIT)
            .mutable(true)
            .build(),
        )
      }
    }
  }

  private fun FunSpec.Builder.initExports(
    guest: CodeBlock,
    instance: CodeBlock,
    value: KtWorld.ExternalApis,
  ) {
    for (item in value.items) {
      when (item) {
        is KtFunction -> {
          addStatement(
            "%L.%N = %L.export(%S)",
            guest,
            item.ktName,
            instance,
            item.name,
          )
        }

        is KtWorld.ExternalApis.InterfaceProperty -> {
          val type = index[item.type]?.declaration as KtInterface
          for (function in type.functions) {
            addStatement(
              "%L.%N.%N = %L.export(%S)",
              guest,
              type.instanceName,
              function.ktName,
              instance,
              function.name,
            )
          }
        }
      }
    }
  }

  private fun FunSpec.Builder.initImports(
    bridge: CodeBlock,
    store: CodeBlock,
    value: WorldIndex.Entry,
  ) {
    when (value.declaration) {
      is KtResource -> {
        val receiver = Receiver.Id(
          bridge = bridge,
          type = value.declaration.type,
        )

        for (function in value.declaration.functions) {
          if (value.host) {
            addHostFunction(
              bridge,
              store,
              receiver,
              function,
            )
          }
        }
      }

      else -> {} // TODO
    }
  }

  private fun FunSpec.Builder.initImports(
    bridge: CodeBlock,
    store: CodeBlock,
    receiver: Receiver.Instance,
    value: KtWorld.ExternalApis,
  ) {
    for (item in value.items) {
      when (item) {
        is KtFunction -> {
          addHostFunction(
            bridge = bridge,
            store = store,
            receiver = receiver,
            value = item,
          )
        }

        is KtWorld.ExternalApis.InterfaceProperty -> {
          val type = index[item.type]?.declaration as KtInterface
          for (function in type.functions) {
            addHostFunction(
              bridge = bridge, store = store,
              receiver = Receiver.Instance(
                CodeBlock.of("%L.%N", receiver.codeBlock, item.instanceName),
              ),
              value = function,
            )
          }
        }
      }
    }
  }

  private fun FunSpec.Builder.addHostFunction(
    bridge: CodeBlock,
    store: CodeBlock,
    receiver: Receiver,
    value: KtFunction,
  ) {
    if (!value.isSupported) return // TODO

    val block = CodeBlock.builder()

    val abiParameterTypes = buildCodeBlock {
      when (receiver) {
        is Receiver.Id -> add("%T.I32", Symbols.ChicoryRuntime.ValType)
        else -> {}
      }
      for (parameter in value.parameters) {
        if (isNotEmpty()) add(", ")
        add(parameter.type.toValType())
      }
    }

    var argIndex = 0
    when (receiver) {
      is Receiver.Id -> {
        block.addStatement(
          "val %N = %L",
          "self",
          receiver.codeBlock(CodeBlock.of("%N[%L]", "args", argIndex++)),
        )
      }

      is Receiver.Instance -> {
        block.addStatement(
          "val %N = %L",
          "self",
          receiver.codeBlock,
        )
      }
    }

    if (value.returnType != null) {
      block.add("val %N = ", "result")
    }
    block.add("%N.%N(⇥\n", "self", value.ktName)
    for (parameter in value.parameters) {
      block.add(
        "%L,\n",
        hostAbiToApi(
          bridge = bridge,
          type = parameter.type,
          abiValue = CodeBlock.of("%N[%L]", "args", argIndex++),
        ),
      )
    }
    block.add("⇤)\n")
    if (value.returnType != null) {
      block.add(
        "return@%T longArrayOf(%L)",
        Symbols.ChicoryRuntime.WasmFunctionHandle,
        hostApiToAbi(bridge, value.returnType, CodeBlock.of("%N", "result")),
      )
    } else {
      block.add(
        "return@%T longArrayOf()",
        Symbols.ChicoryRuntime.WasmFunctionHandle,
      )
    }

    addCode(
      """
      |%L.addFunction(
      |  %T(
      |    %L,
      |    %S,
      |    %T.of(
      |      listOf(%L),
      |      listOf(%L),
      |    ),
      |    %T { instance, args ->
      |      ⇥⇥⇥%L⇤⇤⇤
      |    },
      |  )
      |)
      |
      """.trimMargin(),
      store,
      Symbols.ChicoryRuntime.HostFunction,
      value.name.moduleName?.let { CodeBlock.of("%S", it) } ?: CodeBlock.of("null"),
      value.name.abiName,
      Symbols.ChicoryRuntime.FunctionType,
      abiParameterTypes,
      value.returnType?.toValType() ?: CodeBlock.of(""),
      Symbols.ChicoryRuntime.WasmFunctionHandle,
      block.build(),
    )
  }

  internal sealed interface Receiver {
    data class Instance(
      val codeBlock: CodeBlock,
    ) : Receiver

    data class Id(
      val bridge: CodeBlock,
      val type: ClassName,
    ) : Receiver {
      val name: String
        get() = "self"

      fun codeBlock(id: CodeBlock) = CodeBlock.of(
        "%L.%M<%T>(%L)",
        bridge,
        Symbols.Brevity.HostBridgeGet,
        type,
        id,
      )
    }
  }
}

private val KtWorld.ExternalApis.InterfaceProperty.bridgeType: ClassName
  get() = ClassName(
    packageName = type.packageName,
    simpleNames = type.simpleNames.map { "Bridge${it}" },
  )

private val KtNewService.bridgeType: ClassName
  get() = ClassName(
    packageName = type.packageName,
    simpleNames = type.simpleNames.map { "Bridge${it}" },
  )

private val KtWorld.ExternalApis.bridgeType: ClassName
  get() = ClassName(
    packageName = type.packageName,
    simpleNames = type.simpleNames.map { "Bridge${it}" },
  )

private fun KtTypeName.toValType() =
  CodeBlock.of("%T.I32", Symbols.ChicoryRuntime.ValType)
