package dev.wasmo.brevity.kotlin.generator

import com.squareup.kotlinpoet.ClassName
import com.squareup.kotlinpoet.CodeBlock
import com.squareup.kotlinpoet.FileSpec
import com.squareup.kotlinpoet.FunSpec
import com.squareup.kotlinpoet.KModifier
import com.squareup.kotlinpoet.LambdaTypeName
import com.squareup.kotlinpoet.ParameterSpec
import com.squareup.kotlinpoet.ParameterizedTypeName.Companion.parameterizedBy
import com.squareup.kotlinpoet.PropertySpec
import com.squareup.kotlinpoet.TypeSpec
import com.squareup.kotlinpoet.UNIT
import com.squareup.kotlinpoet.buildCodeBlock
import dev.wasmo.brevity.Annotation

class HostGenerator(
  private val index: WorldIndex,
  private val services: List<KtService>,
) {
  fun generate(): List<FileSpec> {
    return services.groupBy { it.type.packageName }
      .mapNotNull { (`package`, packageServices) ->
        FileSpec.builder(`package`, "Host")
          .addFileComment("Generated by Brevity. Do not edit.")
          .apply {
            for (service in packageServices) {
              if (service is KtWorld) {
                addFunction(worldFactoryFunction(service))
              }

              val typeSpec = serviceToHost(service) ?: continue
              addType(typeSpec)
            }
          }
          .build()
          .takeIf { it.members.isNotEmpty() }
      }
  }

  private fun worldFactoryFunction(value: KtWorld): FunSpec {
    // The implemented World interface uses the interface types; everything else uses the
    // implementation types.
    val worldType = Symbols.Brevity.World.parameterizedBy(
      value.host?.type ?: UNIT,
      value.guest?.type ?: UNIT,
    )

    val hostFactory = ParameterSpec.builder(
      "hostFactory",
      LambdaTypeName.get(
        parameters = listOf(ParameterSpec.unnamed(value.guest?.type ?: UNIT)),
        returnType = value.host?.type ?: UNIT,
      ),
    ).build()

    return FunSpec.builder("World")
      .receiver(value.type)
      .addParameter(hostFactory)
      .returns(worldType)
      .apply {
        addStatement("val %N = %T()", "bridge", Symbols.Brevity.HostBridge)

        if (value.guest != null) {
          addStatement("val %N = %T(%N)", "guest", value.guest.bridgeType, "bridge")
        } else {
          addStatement("val %N = %T", "guest", UNIT)
        }

        addStatement("val %N = %N(%N)", "host", "hostFactory", "guest")

        addStatement(
          "return %T(%N, %N, %N)",
          value.bridgeType,
          "bridge",
          "guest",
          "host",
        )
      }
      .build()
  }

  private fun functionToHost(value: KtFunction) = FunSpec.builder(value.ktName)
    .addModifiers(KModifier.OVERRIDE)
    .apply {
      if (value.returnType != null) {
        addCode("val %N = ", "result")
      }
      addCode("%N.apply(⇥\n", value.ktName)

      for (parameter in value.parameters) {
        addParameter(parameter.name, parameter.type.apiType)
        addCode(
          hostApiToAbi(
            bridge = CodeBlock.of("%N", "bridge"),
            type = parameter.type,
            apiValue = CodeBlock.of("%N", parameter.name),
          ),
        )
        addCode(",\n")
      }
      addCode("⇤)\n")

      if (value.returnType != null) {
        addCode(
          "return %L",
          hostAbiToApi(
            bridge = CodeBlock.of("%N", "bridge"),
            type = value.returnType,
            abiValue = CodeBlock.of("result[%L]", 0),
          ),
        )
        returns(value.returnType.apiType)
      }
    }
    .build()

  private fun serviceToHost(value: KtService): TypeSpec? {
    if (!value.hasInstanceMembers) return null

    val builder = TypeSpec.classBuilder(value.bridgeType)
      .addModifiers(KModifier.INTERNAL)

    if (value !is KtWorld) {
      builder.addSuperinterface(value.type)
    }

    val constructor = FunSpec.constructorBuilder()

    constructor.addParameter("bridge", Symbols.Brevity.HostBridge)
    builder.addProperty(
      PropertySpec.builder("bridge", Symbols.Brevity.HostBridge)
        .addModifiers(KModifier.PRIVATE)
        .initializer("bridge")
        .build(),
    )

    if (value is KtWorld) {
      val guestType = value.guest?.bridgeType ?: UNIT
      val hostType = value.host?.type ?: UNIT

      builder.addSuperinterface(
        Symbols.Brevity.World.parameterizedBy(
          value.host?.type ?: UNIT,
          value.guest?.type ?: UNIT,
        ),
      )

      constructor.addParameter("guest", guestType)
      builder.addProperty(
        PropertySpec.builder("guest", guestType)
          .addModifiers(KModifier.OVERRIDE)
          .initializer("guest")
          .build(),
      )

      constructor.addParameter("host", hostType)
      builder.addProperty(
        PropertySpec.builder("host", hostType)
          .addModifiers(KModifier.OVERRIDE)
          .initializer("host")
          .build(),
      )

      builder.addFunction(
        FunSpec.builder("initExports")
          .addModifiers(KModifier.OVERRIDE)
          .addParameter("instance", Symbols.ChicoryRuntime.Instance)
          .apply {
            if (value.guest != null) {
              initExports(
                guest = CodeBlock.of("%N", "guest"),
                instance = CodeBlock.of("%N", "instance"),
                value = value.guest,
              )
            }
          }
          .build(),
      )

      builder.addFunction(
        FunSpec.builder("initImports")
          .addModifiers(KModifier.OVERRIDE)
          .addParameter("store", Symbols.ChicoryRuntime.Store)
          .apply {
            if (value.host != null) {
              val receiver = Receiver.Instance(
                codeBlock = CodeBlock.of("%N", "host"),
              )
              initImports(
                bridge = CodeBlock.of("%N", "bridge"),
                store = CodeBlock.of("%N", "store"),
                receiver = receiver,
                value = value.host,
              )
            }
            for (entry in index.map.values) {
              initImports(
                bridge = CodeBlock.of("%N", "bridge"),
                store = CodeBlock.of("%N", "store"),
                value = entry,
              )
            }
          }
          .build(),
      )
    }

    for (service in value.services) {
      if (value !is KtWorld) {
        builder.addProperty(
          PropertySpec.builder(service.instanceName, service.bridgeType)
            .addModifiers(KModifier.OVERRIDE)
            .initializer("%T(%N)", service.bridgeType, "bridge")
            .build(),
        )
      }

      if (value.type == service.type.enclosingClassName()) {
        val typeSpec = serviceToHost(service) ?: continue
        builder.addType(typeSpec)
      }
    }

    for (function in value.functions) {
      builder.addFunction(functionToHost(function))
      builder.addProperty(
        PropertySpec.builder(function.ktName, Symbols.ChicoryRuntime.ExportFunction)
          .addModifiers(KModifier.INTERNAL, KModifier.LATEINIT)
          .mutable(true)
          .build(),
      )
    }

    builder.primaryConstructor(constructor.build())

    return builder.build()
  }

  private fun FunSpec.Builder.initExports(
    guest: CodeBlock,
    instance: CodeBlock,
    value: KtService,
  ) {
    for (function in value.functions) {
      addStatement(
        "%L.%N = %L.export(%S)",
        guest,
        function.ktName,
        instance,
        function.name,
      )
    }
    for (service in value.services) {
      initExports(
        guest = CodeBlock.of("%L.%N", guest, service.instanceName),
        instance = instance,
        value = service,
      )
    }
  }

  private fun FunSpec.Builder.initImports(
    bridge: CodeBlock,
    store: CodeBlock,
    value: WorldIndex.Entry,
  ) {
    when (value.declaration) {
      is KtResource -> {
        val receiver = Receiver.Id(
          bridge = bridge,
          type = value.declaration.type,
        )

        for (function in value.declaration.functions) {
          if (value.host) {
            addHostFunction(
              bridge,
              store,
              receiver,
              function,
            )
          }
        }
      }

      else -> {} // TODO
    }
  }

  private fun FunSpec.Builder.initImports(
    bridge: CodeBlock,
    store: CodeBlock,
    receiver: Receiver.Instance,
    value: KtService,
  ) {
    for (function in value.functions) {
      addHostFunction(bridge, store, receiver, function)
    }
    for (service in value.services) {
      initImports(
        bridge = bridge,
        store = store,
        receiver = Receiver.Instance(
          CodeBlock.of("%L.%N", receiver.codeBlock, service.instanceName),
        ),
        value = service,
      )
    }
  }

  private fun FunSpec.Builder.addHostFunction(
    bridge: CodeBlock,
    store: CodeBlock,
    receiver: Receiver,
    value: KtFunction,
  ) {
    when (value.name.annotation) {
      Annotation.Static, Annotation.Constructor -> return // TODO
      else -> {}
    }

    val block = CodeBlock.builder()

    val abiParameterTypes = buildCodeBlock {
      when (receiver) {
        is Receiver.Id -> add("%T.I32", Symbols.ChicoryRuntime.ValType)
        else -> {}
      }
      for (parameter in value.parameters) {
        if (isNotEmpty()) add(", ")
        add(parameter.type.toValType())
      }
    }

    var argIndex = 0
    when (receiver) {
      is Receiver.Id -> {
        block.addStatement(
          "val %N = %L",
          "self",
          receiver.codeBlock(CodeBlock.of("%N[%L]", "args", argIndex++)),
        )
      }

      is Receiver.Instance -> {
        block.addStatement(
          "val %N = %L",
          "self",
          receiver.codeBlock,
        )
      }
    }

    if (value.returnType != null) {
      block.add("val %N = ", "result")
    }
    block.add("%N.%N(⇥\n", "self", value.ktName)
    for (parameter in value.parameters) {
      block.add(
        "%L,\n",
        hostAbiToApi(
          bridge = bridge,
          type = parameter.type,
          abiValue = CodeBlock.of("%N[%L]", "args", argIndex++),
        ),
      )
    }
    block.add("⇤)\n")
    if (value.returnType != null) {
      block.add(
        "return@%T longArrayOf(%L)",
        Symbols.ChicoryRuntime.WasmFunctionHandle,
        hostApiToAbi(bridge, value.returnType, CodeBlock.of("%N", "result")),
      )
    } else {
      block.add(
        "return@%T longArrayOf()",
        Symbols.ChicoryRuntime.WasmFunctionHandle,
      )
    }

    addCode(
      """
      |%L.addFunction(
      |  %T(
      |    %L,
      |    %S,
      |    %T.of(
      |      listOf(%L),
      |      listOf(%L),
      |    ),
      |    %T { instance, args ->
      |      ⇥⇥⇥%L⇤⇤⇤
      |    },
      |  )
      |)
      |
      """.trimMargin(),
      store,
      Symbols.ChicoryRuntime.HostFunction,
      value.name.moduleName?.let { CodeBlock.of("%S", it) } ?: CodeBlock.of("null"),
      value.name.abiName,
      Symbols.ChicoryRuntime.FunctionType,
      abiParameterTypes,
      value.returnType?.toValType() ?: CodeBlock.of(""),
      Symbols.ChicoryRuntime.WasmFunctionHandle,
      block.build(),
    )
  }

  internal sealed interface Receiver {
    data class Instance(
      val codeBlock: CodeBlock,
    ) : Receiver

    data class Id(
      val bridge: CodeBlock,
      val type: ClassName,
    ) : Receiver {
      val name: String
        get() = "self"

      fun codeBlock(id: CodeBlock) = CodeBlock.of(
        "%L.%M<%T>(%L)",
        bridge,
        Symbols.Brevity.HostBridgeGet,
        type,
        id,
      )
    }
  }
}

private val KtService.bridgeType: ClassName
  get() = ClassName(
    packageName = type.packageName,
    simpleNames = type.simpleNames.map { "Bridge${it}" },
  )

private fun KtTypeName.toValType() =
  CodeBlock.of("%T.I32", Symbols.ChicoryRuntime.ValType)
