package dev.wasmo.brevity.kotlin.generator

import com.squareup.kotlinpoet.AnnotationSpec
import com.squareup.kotlinpoet.ClassName
import com.squareup.kotlinpoet.CodeBlock
import com.squareup.kotlinpoet.FileSpec
import com.squareup.kotlinpoet.MemberSpecHolder
import com.squareup.kotlinpoet.TypeSpec
import com.squareup.kotlinpoet.TypeSpecHolder
import com.squareup.kotlinpoet.joinToCode
import dev.wasmo.brevity.kotlin.generator.QualifiedSpec.SourceSet
import okio.FileSystem
import okio.Path

/**
 * A flat list of specs that can be used to produce source files.
 */
data class ProjectSpec(
  private val specs: List<QualifiedSpec>,
) {
  /**
   * We have a flat of types that each know their parent element (a file or another type). We need
   * to convert this into a structured set of files. For simplicity, we just perform _N_ rounds,
   * successively adding leaf types to their parent types.
   */
  fun fileSpecs(sourceSet: SourceSet): List<FileSpec> {
    val sourceSetSpecs = specs.filter { it.parent.sourceSet == sourceSet }

    val typeEntries = mutableMapOf<ClassName, Entry<TypeSpec.Builder>>()
    var maxDepth = 1
    for (spec in sourceSetSpecs) {
      if (spec is QualifiedSpec.Type) {
        typeEntries[spec.className] = Entry(spec.type.toBuilder())
        maxDepth = maxOf(spec.className.simpleNames.size, maxDepth)
      }
    }

    // From deepest to shallowest, add specs to their parent type.
    for (depth in maxDepth - 1 downTo 1) {
      for (spec in sourceSetSpecs) {
        val parentType = spec.parent as? QualifiedSpec.Parent.Type ?: continue
        if (depth != parentType.className.simpleNames.size) continue

        val entry = typeEntries[parentType.className]
          ?: error("parent symbol ${parentType.className} not declared")

        entry.add(spec, typeEntries)
      }
    }

    // Now add top-level specs to their parent file.
    val fileEntries = mutableMapOf<QualifiedSpec.Parent.File, Entry<FileSpec.Builder>>()
    for (spec in sourceSetSpecs) {
      val parentFile = spec.parent as? QualifiedSpec.Parent.File ?: continue

      val entry = fileEntries.getOrPut(parentFile) {
        Entry(FileSpec.builder(parentFile.packageName, parentFile.fileName))
      }

      entry.add(spec, typeEntries)
    }

    return fileEntries.values.map { entry ->
      entry.build()
    }
  }

  /** A type or a file that can accept child declarations. */
  private class Entry<T>(
    val builder: T,
  ) where T : TypeSpecHolder.Builder<T>, T : MemberSpecHolder.Builder<T> {
    val paths = mutableSetOf<Path>()
    val optIns = mutableSetOf<ClassName>()

    fun add(
      spec: QualifiedSpec,
      typeEntries: Map<ClassName, Entry<TypeSpec.Builder>>,
    ) {
      paths += spec.locations.map { it.path }
      optIns += spec.optIns

      when (spec) {
        is QualifiedSpec.Function -> builder.addFunction(spec.function)
        is QualifiedSpec.Property -> builder.addProperty(spec.property)
        is QualifiedSpec.Type -> {
          val typeSpec = typeEntries[spec.className]!!.builder.build()
          builder.addType(typeSpec)
        }
      }
    }
  }

  /** Add file-level stuff (comments and opt-ins) to return a complete file. */
  private fun Entry<FileSpec.Builder>.build(): FileSpec {
    builder.addFileComment("Generated by Brevity. Do not edit.")
    for (path in paths.sorted()) {
      builder.addFileComment("\n  $path")
    }

    if (optIns.isNotEmpty()) {
      builder.addAnnotation(
        AnnotationSpec.builder(Symbols.Kotlin.OptIn)
          .addMember(optIns.sortedBy { it.simpleName }.joinToCode { CodeBlock.of("%T::class", it) })
          .build(),
      )
    }

    return builder.build()
  }

  fun writeTo(
    fileSystem: FileSystem,
    commonMain: Path,
    wasmWasiMain: Path,
    jvmMain: Path,
  ) {
    writeTo(fileSystem, SourceSet.CommonMain, commonMain)
    writeTo(fileSystem, SourceSet.WasmWasiMain, wasmWasiMain)
    writeTo(fileSystem, SourceSet.JvmMain, jvmMain)
  }

  private fun writeTo(
    fileSystem: FileSystem,
    sourceSet: SourceSet,
    directory: Path,
  ) {
    for (fileSpec in fileSpecs(sourceSet)) {
      val path = directory / fileSpec.relativePath
      path.parent?.let { parentDirectory ->
        fileSystem.createDirectories(parentDirectory)
      }
      fileSystem.write(path) {
        writeUtf8(fileSpec.toString())
      }
    }
  }
}
