package dev.wasmo.brevity.kotlin.generator

import com.squareup.kotlinpoet.AnnotationSpec
import com.squareup.kotlinpoet.ClassName
import com.squareup.kotlinpoet.CodeBlock
import com.squareup.kotlinpoet.FileSpec
import com.squareup.kotlinpoet.MemberSpecHolder
import com.squareup.kotlinpoet.TypeSpec
import com.squareup.kotlinpoet.TypeSpecHolder
import com.squareup.kotlinpoet.joinToCode
import dev.wasmo.brevity.kotlin.generator.QualifiedSpec.SourceSet
import okio.FileSystem
import okio.Path

/**
 * A flat list of specs that can be used to produce source files.
 */
data class ProjectSpec(
  private val specs: List<QualifiedSpec>,
) {
  /**
   * We have a flat of types that each know their parent element (a file or another type). We need
   * to convert this into a structured set of files. For simplicity, we just perform _N_ rounds,
   * successively adding leaf types to their parent types.
   */
  fun fileSpecs(sourceSet: SourceSet): List<FileSpec> {
    val sourceSetSpecs = specs.filter { it.parent.sourceSet == sourceSet }

    val typeEntries = mutableMapOf<ClassName, Entry<TypeSpec.Builder>>()
    var maxDepth = 1
    for (spec in sourceSetSpecs) {
      if (spec is QualifiedSpec.Type) {
        typeEntries[spec.className] = Entry(spec.type.toBuilder()).apply {
          paths += spec.locations.map { it.path }
          optIns += spec.optIns
        }
        maxDepth = maxOf(spec.className.simpleNames.size, maxDepth)
      }
    }

    val fileEntries = mutableMapOf<QualifiedSpec.Parent.File, Entry<FileSpec.Builder>>()

    // From deepest to shallowest, add specs to their parent entry.
    val deepestToShallowest = sourceSetSpecs
      .sortedBy {
        val parent = it.parent as? QualifiedSpec.Parent.Type ?: return@sortedBy 0
        -parent.className.simpleNames.size
      }
    for (spec in deepestToShallowest) {
      val parentEntry = when (val parent = spec.parent) {
        is QualifiedSpec.Parent.Type -> {
          typeEntries[parent.className]
            ?: error("parent symbol ${parent.className} not declared")
        }

        is QualifiedSpec.Parent.File -> {
          fileEntries.getOrPut(parent) {
            Entry(FileSpec.builder(parent.packageName, parent.fileName))
          }
        }
      }

      parentEntry.add(spec, typeEntries)
    }

    return fileEntries.values.map { entry ->
      entry.build()
    }
  }

  /** A type or a file that can accept child declarations. */
  private class Entry<T>(
    val builder: T,
  ) where T : TypeSpecHolder.Builder<T>, T : MemberSpecHolder.Builder<T> {
    val paths = mutableSetOf<Path>()
    val optIns = mutableSetOf<ClassName>()

    fun add(
      spec: QualifiedSpec,
      typeEntries: Map<ClassName, Entry<TypeSpec.Builder>>,
    ) {
      when (spec) {
        is QualifiedSpec.Function -> {
          paths += spec.locations.map { it.path }
          optIns += spec.optIns
          builder.addFunction(spec.function)
        }
        is QualifiedSpec.Property -> {
          paths += spec.locations.map { it.path }
          optIns += spec.optIns
          builder.addProperty(spec.property)
        }
        is QualifiedSpec.Type -> {
          val entry = typeEntries[spec.className]!!
          paths += entry.paths
          optIns += entry.optIns
          builder.addType(entry.builder.build())
        }
      }
    }
  }

  /** Add file-level stuff (comments and opt-ins) to return a complete file. */
  private fun Entry<FileSpec.Builder>.build(): FileSpec {
    builder.addFileComment("Generated by Brevity. Do not edit.")
    for (path in paths.sorted()) {
      builder.addFileComment("\n  $path")
    }

    if (optIns.isNotEmpty()) {
      builder.addAnnotation(
        AnnotationSpec.builder(Symbols.Kotlin.OptIn)
          .addMember(optIns.sortedBy { it.simpleName }.joinToCode { CodeBlock.of("%T::class", it) })
          .build(),
      )
    }

    return builder.build()
  }

  fun writeTo(
    fileSystem: FileSystem,
    commonMain: Path,
    wasmWasiMain: Path,
    jvmMain: Path,
  ) {
    writeTo(fileSystem, SourceSet.CommonMain, commonMain)
    writeTo(fileSystem, SourceSet.WasmWasiMain, wasmWasiMain)
    writeTo(fileSystem, SourceSet.JvmMain, jvmMain)
  }

  private fun writeTo(
    fileSystem: FileSystem,
    sourceSet: SourceSet,
    directory: Path,
  ) {
    for (fileSpec in fileSpecs(sourceSet)) {
      val path = directory / fileSpec.relativePath
      path.parent?.let { parentDirectory ->
        fileSystem.createDirectories(parentDirectory)
      }
      fileSystem.write(path) {
        writeUtf8(fileSpec.toString())
      }
    }
  }
}
