package dev.wasmo.brevity.kotlin.generator

import assertk.assertThat
import assertk.assertions.hasSize
import assertk.assertions.isEqualTo
import dev.wasmo.brevity.BrevityTester
import kotlin.test.Test
import okio.Path.Companion.toPath

class KotlinGeneratorTest {
  private fun tester(): BrevityTester {
    val tester = BrevityTester(
      "clock.wit".toPath() to
        """
        package wasi:clocks@0.2.12;

        /// gets the epoch time
        @since(version = 0.2.0)
        interface wall-clock {
            /// A time and date in seconds plus nanoseconds.
            @since(version = 0.2.0)
            record datetime {
                /// Since 1970.
                seconds: u64,
                /// Always less than 1000000000.
                nanoseconds: u32,
            }

            /// Read the current value of the clock.
            @since(version = 0.2.0)
            now: func() -> datetime;

            /// `pollable` represents a single I/O event which may be ready, or not.
            resource pollable {
                /// Return the readiness of a pollable. This function never blocks.
                ready: func() -> bool;
            }

            /// Lookup error codes.
            variant error-code {
                /// Access denied.
                access-denied,
                /// A catch-all.
                other(option<string>),
            }

            /// File or memory access pattern advisory information.
            enum advice {
                /// No advice.
                normal,
                /// sequentially from lower to higher.
                sequential,
            }

            /// How paths are resolved.
            flags path-flags {
                /// Follow the darn things.
                symlink-follow,
            }

            /// You can do both with an epoch.
            type instant = datetime;
        }
        """.trimIndent(),

      "world.wit".toPath() to
        """
        package wasi:clocks@0.2.12;

        world time {
            import wall-clock;

            /// Execute the command and return an exit code.
            export run: func(
                /// command-line arguments.
                args: list<string>
            ) -> s32;
        }
        """.trimIndent(),
    )

    assertThat(tester.files).hasSize(17)
    return tester
  }

  @Test
  fun `world api`() {
    assertThat(tester()["wit/wasi/clocks/v0_2_12/Time.kt".toPath()]).isEqualTo(
      """
      // Generated by Brevity. Do not edit.
      //   world.wit
      package wit.wasi.clocks.v0_2_12

      import kotlin.Int
      import kotlin.String
      import kotlin.collections.List

      public object Time {
        public interface Guest {
          /**
           * Execute the command and return an exit code.
           *
           * @param args command-line arguments.
           */
          public fun run(args: List<String>): Int
        }

        public interface Host {
          public val wallClock: WallClock
        }
      }

      """.trimIndent(),
    )
  }

  @Test
  fun `world guest`() {
    assertThat(tester()["wit/wasi/clocks/v0_2_12/TimeGuest.kt".toPath()]).isEqualTo(
      """
      // Generated by Brevity. Do not edit.
      //   world.wit
      @file:OptIn(ComponentModelInternalApi::class, ExperimentalWasmInterop::class, UnsafeWasmMemoryApi::class)

      package wit.wasi.clocks.v0_2_12

      import dev.wasmo.brevity.loadString
      import dev.wasmo.brevity.retainWasmExportsForGuestBridge
      import kotlin.Int
      import kotlin.OptIn
      import kotlin.String
      import kotlin.collections.List
      import kotlin.wasm.ExperimentalWasmInterop
      import kotlin.wasm.WasmExport
      import kotlin.wasm.unsafe.ComponentModelInternalApi
      import kotlin.wasm.unsafe.Pointer
      import kotlin.wasm.unsafe.UnsafeWasmMemoryApi

      private lateinit var guest_: Time.Guest

      public var Time.guest: Time.Guest
        get() = guest_
        set(`value`) {
          retainWasmExportsForGuestBridge()
          retainWasmExportsForTime()
          guest_ = `value`
        }

      /**
       * This function does nothing. But by calling it the compiler retains exported symbols that
       * would otherwise be eliminated as unused.
       *
       * https://youtrack.jetbrains.com/issue/KT-88068/
       */
      private fun retainWasmExportsForTime() {
        // Equivalent to 'if (true) return', but immune to dead code elimination.
        if ("".hashCode() == 0) return
        run_export(0, 0)
      }

      @WasmExport("run")
      private fun run_export(argsAddress: Int, argsSize: Int): Int {
        val listAddress = Pointer(argsAddress.toUInt())
        val length = argsSize
        val list = List<String>(length) { i ->
          val elementAddress = listAddress + i * 8
          val stringAddress = (elementAddress).loadInt()
          val stringByteCount = (elementAddress + 4).loadInt()
          Pointer(stringAddress.toUInt()).loadString(stringByteCount)
        }
        val result = guest_.run(
          args = list,
        )
        return result
      }

      """.trimIndent(),
    )
  }

  @Test
  fun `world host`() {
    assertThat(tester()["wit/wasi/clocks/v0_2_12/TimeHost.kt".toPath()]).isEqualTo(
      """
      // Generated by Brevity. Do not edit.
      //   world.wit
      package wit.wasi.clocks.v0_2_12

      import com.dylibso.chicory.runtime.ExportFunction
      import com.dylibso.chicory.runtime.HostFunction
      import com.dylibso.chicory.runtime.Instance
      import com.dylibso.chicory.runtime.Store
      import com.dylibso.chicory.runtime.WasmFunctionHandle
      import com.dylibso.chicory.wasm.types.FunctionType
      import com.dylibso.chicory.wasm.types.ValType
      import dev.wasmo.brevity.HostBridge
      import dev.wasmo.brevity.World
      import kotlin.Int
      import kotlin.String
      import kotlin.collections.List
      import kotlin.text.encodeToByteArray

      public fun Time.World(hostFactory: (Time.Guest) -> Time.Host): World<Time.Host, Time.Guest> {
        val bridge = HostBridge()
        val guest = BridgeTime.BridgeGuest(bridge)
        val host = hostFactory(guest)
        return BridgeTime(bridge, guest, host)
      }

      internal class BridgeTime(
        private val bridge: HostBridge,
        override val guest: BridgeGuest,
        override val host: Time.Host,
      ) : World<Time.Host, Time.Guest> {
        override fun initExports(instance: Instance) {
          this.bridge.init(instance)
          guest.run = instance.export("run")
        }

        override fun initImports(store: Store) {
          store.addFunction(
            HostFunction(
              "wasi:clocks/wall-clock@0.2.12",
              "now",
              FunctionType.of(
                listOf(ValType.I32),
                listOf(),
              ),
              WasmFunctionHandle { instance, args ->
                val self = host.wallClock
                val result = self.now()
                val resultParameter = args[0].toInt()
                store_WallClock_Datetime_host(bridge, resultParameter, result)
                return@WasmFunctionHandle longArrayOf()
              },
            )
          )
        }

        internal class BridgeGuest(
          private val bridge: HostBridge,
        ) : Time.Guest {
          internal lateinit var run: ExportFunction

          override fun run(args: List<String>): Int {
            val listAddress = bridge.allocate(args.size * 8)
            for (i in args.indices) {
              val elementAddress = listAddress + i * 8
              val byteArray = args[i].encodeToByteArray()
              val stringAddress = bridge.allocate(byteArray.size)
              bridge.memory.write(stringAddress, byteArray)
              val stringAddress_ = stringAddress
              val stringByteCount = byteArray.size
              bridge.memory.writeI32(elementAddress, stringAddress_)
              bridge.memory.writeI32(elementAddress + 4, stringByteCount)
            }
            val result = run.apply(
              listAddress.toLong(),
              args.size.toLong(),
            )
            return result[0].toInt()
          }
        }

        internal class BridgeHost(
          private val bridge: HostBridge,
        ) : Time.Host {
          override val wallClock: BridgeWallClock = BridgeWallClock(bridge)
        }
      }

      """.trimIndent(),
    )
  }

  @Test
  fun `interface api`() {
    assertThat(tester()["wit/wasi/clocks/v0_2_12/WallClock.kt".toPath()]).isEqualTo(
      """
      // Generated by Brevity. Do not edit.
      //   clock.wit
      package wit.wasi.clocks.v0_2_12

      import dev.wasmo.brevity.Resource
      import kotlin.Boolean
      import kotlin.String
      import kotlin.UInt
      import kotlin.ULong
      import kotlin.jvm.JvmInline

      /**
       * gets the epoch time
       */
      public interface WallClock {
        /**
         * Read the current value of the clock.
         */
        public fun now(): Datetime

        /**
         * A time and date in seconds plus nanoseconds.
         */
        public data class Datetime(
          /**
           * Since 1970.
           */
          public val seconds: ULong,
          /**
           * Always less than 1000000000.
           */
          public val nanoseconds: UInt,
        )

        /**
         * `pollable` represents a single I/O event which may be ready, or not.
         */
        public interface Pollable : Resource {
          /**
           * Return the readiness of a pollable. This function never blocks.
           */
          public fun ready(): Boolean
        }

        /**
         * Lookup error codes.
         */
        public sealed interface ErrorCode {
          /**
           * Access denied.
           */
          public data object AccessDenied : ErrorCode

          /**
           * A catch-all.
           */
          public data class Other(
            public val `value`: String?,
          ) : ErrorCode
        }

        /**
         * File or memory access pattern advisory information.
         */
        public enum class Advice {
          /**
           * No advice.
           */
          Normal,
          /**
           * sequentially from lower to higher.
           */
          Sequential,
        }

        /**
         * How paths are resolved.
         */
        public data class PathFlags(
          /**
           * Follow the darn things.
           */
          public val symlinkFollow: Boolean,
        )

        /**
         * You can do both with an epoch.
         */
        @JvmInline
        public value class Instant(
          public val `value`: Datetime,
        )
      }

      """.trimIndent(),
    )
  }

  @Test
  fun `enum guest`() {
    assertThat(tester()["wit/wasi/clocks/v0_2_12/WallClockAdviceGuest.kt".toPath()]).isEqualTo(
      """
      // Generated by Brevity. Do not edit.
      //   clock.wit
      @file:OptIn(ComponentModelInternalApi::class, ExperimentalWasmInterop::class, UnsafeWasmMemoryApi::class)

      package wit.wasi.clocks.v0_2_12

      import dev.wasmo.brevity.GuestBridge
      import kotlin.Byte
      import kotlin.Int
      import kotlin.OptIn
      import kotlin.wasm.ExperimentalWasmInterop
      import kotlin.wasm.unsafe.ComponentModelInternalApi
      import kotlin.wasm.unsafe.Pointer
      import kotlin.wasm.unsafe.UnsafeWasmMemoryApi

      public fun store_WallClock_Advice_guest(
        bridge: GuestBridge,
        address: Pointer,
        value_: WallClock.Advice,
      ) {
        val adviceDiscriminator: Byte = when (val advice = value_) {
          WallClock.Advice.Normal -> {
            0
          }
          WallClock.Advice.Sequential -> {
            1
          }
        }
        (address).storeByte(adviceDiscriminator)
      }

      public fun lowerFlat_WallClock_Advice_guest(bridge: GuestBridge, value_: WallClock.Advice): Int {
        val advice = value_
        val adviceDiscriminator = when (advice) {
          WallClock.Advice.Normal -> {
            0
          }
          WallClock.Advice.Sequential -> {
            1
          }
        }
        return adviceDiscriminator
      }

      public fun load_WallClock_Advice_guest(bridge: GuestBridge, address: Pointer): WallClock.Advice {
        val advice = when ((address).loadByte().toInt()) {
          0 -> {
            WallClock.Advice.Normal
          }
          1 -> {
            WallClock.Advice.Sequential
          }
          else -> error("unexpected case")
        }
        return advice
      }

      public fun liftFlat_WallClock_Advice_guest(bridge: GuestBridge, value_: Int): WallClock.Advice {
        val advice = when (value_) {
          0 -> {
            WallClock.Advice.Normal
          }
          1 -> {
            WallClock.Advice.Sequential
          }
          else -> error("unexpected case")
        }
        return advice
      }

      """.trimIndent(),
    )
  }

  @Test
  fun `enum host`() {
    assertThat(tester()["wit/wasi/clocks/v0_2_12/WallClockAdviceHost.kt".toPath()]).isEqualTo(
      """
      // Generated by Brevity. Do not edit.
      //   clock.wit
      package wit.wasi.clocks.v0_2_12

      import dev.wasmo.brevity.HostBridge
      import kotlin.Byte
      import kotlin.Int

      public fun store_WallClock_Advice_host(
        bridge: HostBridge,
        address: Int,
        value_: WallClock.Advice,
      ) {
        val adviceDiscriminator: Byte = when (val advice = value_) {
          WallClock.Advice.Normal -> {
            0
          }
          WallClock.Advice.Sequential -> {
            1
          }
        }
        bridge.memory.writeByte(address, adviceDiscriminator)
      }

      public fun lowerFlat_WallClock_Advice_host(bridge: HostBridge, value_: WallClock.Advice): Int {
        val advice = value_
        val adviceDiscriminator = when (advice) {
          WallClock.Advice.Normal -> {
            0
          }
          WallClock.Advice.Sequential -> {
            1
          }
        }
        return adviceDiscriminator
      }

      public fun load_WallClock_Advice_host(bridge: HostBridge, address: Int): WallClock.Advice {
        val advice = when (bridge.memory.read(address).toInt()) {
          0 -> {
            WallClock.Advice.Normal
          }
          1 -> {
            WallClock.Advice.Sequential
          }
          else -> error("unexpected case")
        }
        return advice
      }

      public fun liftFlat_WallClock_Advice_host(bridge: HostBridge, value_: Int): WallClock.Advice {
        val advice = when (value_) {
          0 -> {
            WallClock.Advice.Normal
          }
          1 -> {
            WallClock.Advice.Sequential
          }
          else -> error("unexpected case")
        }
        return advice
      }

      """.trimIndent(),
    )
  }

  @Test
  fun `record guest`() {
    assertThat(tester()["wit/wasi/clocks/v0_2_12/WallClockDatetimeGuest.kt".toPath()]).isEqualTo(
      """
      // Generated by Brevity. Do not edit.
      //   clock.wit
      @file:OptIn(ComponentModelInternalApi::class, ExperimentalWasmInterop::class, UnsafeWasmMemoryApi::class)

      package wit.wasi.clocks.v0_2_12

      import dev.wasmo.brevity.CallBuilder
      import dev.wasmo.brevity.GuestBridge
      import kotlin.Int
      import kotlin.Long
      import kotlin.OptIn
      import kotlin.wasm.ExperimentalWasmInterop
      import kotlin.wasm.unsafe.ComponentModelInternalApi
      import kotlin.wasm.unsafe.Pointer
      import kotlin.wasm.unsafe.UnsafeWasmMemoryApi

      public fun store_WallClock_Datetime_guest(
        bridge: GuestBridge,
        address: Pointer,
        value_: WallClock.Datetime,
      ) {
        (address).storeLong(value_.seconds.toLong())
        (address + 8).storeInt(value_.nanoseconds.toInt())
      }

      public fun lowerFlat_WallClock_Datetime_guest(
        bridge: GuestBridge,
        value_: WallClock.Datetime,
        callBuilder: CallBuilder,
      ) {
        val tuple = value_
        callBuilder.put(tuple.seconds.toLong())
        callBuilder.put(tuple.nanoseconds.toInt())
      }

      public fun load_WallClock_Datetime_guest(bridge: GuestBridge, address: Pointer): WallClock.Datetime = WallClock.Datetime(
        seconds = (address).loadLong().toULong(),
        nanoseconds = (address + 8).loadInt().toUInt(),
      )

      public fun liftFlat_WallClock_Datetime_guest(
        bridge: GuestBridge,
        value_: Long,
        value1: Int,
      ): WallClock.Datetime = WallClock.Datetime(
        seconds = value_.toULong(),
        nanoseconds = value1.toUInt(),
      )

      """.trimIndent(),
    )
  }

  @Test
  fun `record host`() {
    assertThat(tester()["wit/wasi/clocks/v0_2_12/WallClockDatetimeHost.kt".toPath()]).isEqualTo(
      """
      // Generated by Brevity. Do not edit.
      //   clock.wit
      package wit.wasi.clocks.v0_2_12

      import dev.wasmo.brevity.CallBuilder
      import dev.wasmo.brevity.HostBridge
      import kotlin.Int
      import kotlin.Long

      public fun store_WallClock_Datetime_host(
        bridge: HostBridge,
        address: Int,
        value_: WallClock.Datetime,
      ) {
        bridge.memory.writeLong(address, value_.seconds.toLong())
        bridge.memory.writeI32(address + 8, value_.nanoseconds.toInt())
      }

      public fun lowerFlat_WallClock_Datetime_host(
        bridge: HostBridge,
        value_: WallClock.Datetime,
        callBuilder: CallBuilder,
      ) {
        val tuple = value_
        callBuilder.put(tuple.seconds.toLong())
        callBuilder.put(tuple.nanoseconds.toInt())
      }

      public fun load_WallClock_Datetime_host(bridge: HostBridge, address: Int): WallClock.Datetime = WallClock.Datetime(
        seconds = bridge.memory.readLong(address).toULong(),
        nanoseconds = bridge.memory.readInt(address + 8).toUInt(),
      )

      public fun liftFlat_WallClock_Datetime_host(
        bridge: HostBridge,
        value_: Long,
        value1: Int,
      ): WallClock.Datetime = WallClock.Datetime(
        seconds = value_.toULong(),
        nanoseconds = value1.toUInt(),
      )

      """.trimIndent(),
    )
  }

  @Test
  fun `variant guest`() {
    assertThat(tester()["wit/wasi/clocks/v0_2_12/WallClockErrorCodeGuest.kt".toPath()]).isEqualTo(
      """
      // Generated by Brevity. Do not edit.
      //   clock.wit
      @file:OptIn(ComponentModelInternalApi::class, ExperimentalWasmInterop::class, UnsafeWasmMemoryApi::class)

      package wit.wasi.clocks.v0_2_12

      import dev.wasmo.brevity.CallBuilder
      import dev.wasmo.brevity.GuestBridge
      import dev.wasmo.brevity.loadString
      import dev.wasmo.brevity.storeByteArray
      import kotlin.Byte
      import kotlin.Int
      import kotlin.OptIn
      import kotlin.text.encodeToByteArray
      import kotlin.wasm.ExperimentalWasmInterop
      import kotlin.wasm.unsafe.ComponentModelInternalApi
      import kotlin.wasm.unsafe.Pointer
      import kotlin.wasm.unsafe.UnsafeWasmMemoryApi
      import kotlin.wasm.unsafe.withScopedMemoryAllocator

      public fun store_WallClock_ErrorCode_guest(
        bridge: GuestBridge,
        address: Pointer,
        value_: WallClock.ErrorCode,
      ) {
        withScopedMemoryAllocator { memoryAllocator ->
          val errorCodeDiscriminator: Byte = when (val errorCode = value_) {
            WallClock.ErrorCode.AccessDenied -> {
              0
            }
            is WallClock.ErrorCode.Other -> {
              val optionalDiscriminator: Byte = when (val optional = errorCode.value) {
                null -> {
                  0
                }
                else -> {
                  val byteArray = optional.encodeToByteArray()
                  val stringAddress = memoryAllocator.allocate(byteArray.size)
                  stringAddress.storeByteArray(byteArray)
                  val stringAddress_ = stringAddress.address.toInt()
                  val stringByteCount = byteArray.size
                  (address + 8).storeInt(stringAddress_)
                  (address + 12).storeInt(stringByteCount)
                  1
                }
              }
              (address + 4).storeByte(optionalDiscriminator)
              1
            }
          }
          (address).storeByte(errorCodeDiscriminator)
        }
      }

      public fun lowerFlat_WallClock_ErrorCode_guest(
        bridge: GuestBridge,
        value_: WallClock.ErrorCode,
        callBuilder: CallBuilder,
      ) {
        withScopedMemoryAllocator { memoryAllocator ->
          val errorCode = value_
          var errorCodeCoreValueBits0 = 0
          var errorCodeCoreValueBits1 = 0
          var errorCodeCoreValueBits2 = 0
          val errorCodeDiscriminator = when (errorCode) {
            WallClock.ErrorCode.AccessDenied -> {
              0
            }
            is WallClock.ErrorCode.Other -> {
              val optional = errorCode.value
              var optionalCoreValueBits0 = 0
              var optionalCoreValueBits1 = 0
              val optionalDiscriminator = when (optional) {
                null -> {
                  0
                }
                else -> {
                  val byteArray = optional.encodeToByteArray()
                  val stringAddress = memoryAllocator.allocate(byteArray.size)
                  stringAddress.storeByteArray(byteArray)
                  optionalCoreValueBits0 = stringAddress.address.toInt()
                  optionalCoreValueBits1 = byteArray.size
                  1
                }
              }
              errorCodeCoreValueBits0 = optionalDiscriminator
              errorCodeCoreValueBits1 = optionalCoreValueBits0
              errorCodeCoreValueBits2 = optionalCoreValueBits1
              1
            }
          }
          callBuilder.put(errorCodeDiscriminator)
          callBuilder.put(errorCodeCoreValueBits0)
          callBuilder.put(errorCodeCoreValueBits1)
          callBuilder.put(errorCodeCoreValueBits2)
        }
      }

      public fun load_WallClock_ErrorCode_guest(bridge: GuestBridge, address: Pointer): WallClock.ErrorCode {
        val errorCode = when ((address).loadByte().toInt()) {
          0 -> {
            WallClock.ErrorCode.AccessDenied
          }
          1 -> {
            val optional = when ((address + 4).loadByte().toInt()) {
              0 -> {
                null
              }
              1 -> {
                val stringAddress = (address + 8).loadInt()
                val stringByteCount = (address + 12).loadInt()
                Pointer(stringAddress.toUInt()).loadString(stringByteCount)
              }
              else -> error("unexpected case")
            }
            WallClock.ErrorCode.Other(optional)
          }
          else -> error("unexpected case")
        }
        return errorCode
      }

      public fun liftFlat_WallClock_ErrorCode_guest(
        bridge: GuestBridge,
        value_: Int,
        value1: Int,
        value2: Int,
        value3: Int,
      ): WallClock.ErrorCode {
        val errorCode = when (value_) {
          0 -> {
            WallClock.ErrorCode.AccessDenied
          }
          1 -> {
            val optional = when (value1) {
              0 -> {
                null
              }
              1 -> {
                Pointer(value2.toUInt()).loadString(value3)
              }
              else -> error("unexpected case")
            }
            WallClock.ErrorCode.Other(optional)
          }
          else -> error("unexpected case")
        }
        return errorCode
      }

      """.trimIndent(),
    )
  }

  @Test
  fun `variant host`() {
    assertThat(tester()["wit/wasi/clocks/v0_2_12/WallClockErrorCodeHost.kt".toPath()]).isEqualTo(
      """
      // Generated by Brevity. Do not edit.
      //   clock.wit
      package wit.wasi.clocks.v0_2_12

      import dev.wasmo.brevity.CallBuilder
      import dev.wasmo.brevity.HostBridge
      import kotlin.Byte
      import kotlin.Int
      import kotlin.text.encodeToByteArray

      public fun store_WallClock_ErrorCode_host(
        bridge: HostBridge,
        address: Int,
        value_: WallClock.ErrorCode,
      ) {
        val errorCodeDiscriminator: Byte = when (val errorCode = value_) {
          WallClock.ErrorCode.AccessDenied -> {
            0
          }
          is WallClock.ErrorCode.Other -> {
            val optionalDiscriminator: Byte = when (val optional = errorCode.value) {
              null -> {
                0
              }
              else -> {
                val byteArray = optional.encodeToByteArray()
                val stringAddress = bridge.allocate(byteArray.size)
                bridge.memory.write(stringAddress, byteArray)
                val stringAddress_ = stringAddress
                val stringByteCount = byteArray.size
                bridge.memory.writeI32(address + 8, stringAddress_)
                bridge.memory.writeI32(address + 12, stringByteCount)
                1
              }
            }
            bridge.memory.writeByte(address + 4, optionalDiscriminator)
            1
          }
        }
        bridge.memory.writeByte(address, errorCodeDiscriminator)
      }

      public fun lowerFlat_WallClock_ErrorCode_host(
        bridge: HostBridge,
        value_: WallClock.ErrorCode,
        callBuilder: CallBuilder,
      ) {
        val errorCode = value_
        var errorCodeCoreValueBits0 = 0
        var errorCodeCoreValueBits1 = 0
        var errorCodeCoreValueBits2 = 0
        val errorCodeDiscriminator = when (errorCode) {
          WallClock.ErrorCode.AccessDenied -> {
            0
          }
          is WallClock.ErrorCode.Other -> {
            val optional = errorCode.value
            var optionalCoreValueBits0 = 0
            var optionalCoreValueBits1 = 0
            val optionalDiscriminator = when (optional) {
              null -> {
                0
              }
              else -> {
                val byteArray = optional.encodeToByteArray()
                val stringAddress = bridge.allocate(byteArray.size)
                bridge.memory.write(stringAddress, byteArray)
                optionalCoreValueBits0 = stringAddress
                optionalCoreValueBits1 = byteArray.size
                1
              }
            }
            errorCodeCoreValueBits0 = optionalDiscriminator
            errorCodeCoreValueBits1 = optionalCoreValueBits0
            errorCodeCoreValueBits2 = optionalCoreValueBits1
            1
          }
        }
        callBuilder.put(errorCodeDiscriminator)
        callBuilder.put(errorCodeCoreValueBits0)
        callBuilder.put(errorCodeCoreValueBits1)
        callBuilder.put(errorCodeCoreValueBits2)
      }

      public fun load_WallClock_ErrorCode_host(bridge: HostBridge, address: Int): WallClock.ErrorCode {
        val errorCode = when (bridge.memory.read(address).toInt()) {
          0 -> {
            WallClock.ErrorCode.AccessDenied
          }
          1 -> {
            val optional = when (bridge.memory.read(address + 4).toInt()) {
              0 -> {
                null
              }
              1 -> {
                val stringAddress = bridge.memory.readInt(address + 8)
                val stringByteCount = bridge.memory.readInt(address + 12)
                bridge.memory.readString(stringAddress, stringByteCount)
              }
              else -> error("unexpected case")
            }
            WallClock.ErrorCode.Other(optional)
          }
          else -> error("unexpected case")
        }
        return errorCode
      }

      public fun liftFlat_WallClock_ErrorCode_host(
        bridge: HostBridge,
        value_: Int,
        value1: Int,
        value2: Int,
        value3: Int,
      ): WallClock.ErrorCode {
        val errorCode = when (value_) {
          0 -> {
            WallClock.ErrorCode.AccessDenied
          }
          1 -> {
            val optional = when (value1) {
              0 -> {
                null
              }
              1 -> {
                bridge.memory.readString(value2, value3)
              }
              else -> error("unexpected case")
            }
            WallClock.ErrorCode.Other(optional)
          }
          else -> error("unexpected case")
        }
        return errorCode
      }

      """.trimIndent(),
    )
  }

  @Test
  fun `interface host`() {
    assertThat(tester()["wit/wasi/clocks/v0_2_12/WallClockHost.kt".toPath()]).isEqualTo(
      """
      // Generated by Brevity. Do not edit.
      //   clock.wit
      package wit.wasi.clocks.v0_2_12

      import com.dylibso.chicory.runtime.ExportFunction
      import dev.wasmo.brevity.HostBridge

      internal class BridgeWallClock(
        private val bridge: HostBridge,
      ) : WallClock {
        internal lateinit var now: ExportFunction

        override fun now(): WallClock.Datetime {
          val result = now.apply(
          )
          return load_WallClock_Datetime_host(bridge, result[0].toInt())
        }
      }

      """.trimIndent(),
    )
  }

  @Test
  fun `type alias guest`() {
    assertThat(tester()["wit/wasi/clocks/v0_2_12/WallClockInstantGuest.kt".toPath()]).isEqualTo(
      """
      // Generated by Brevity. Do not edit.
      //   clock.wit
      @file:OptIn(ComponentModelInternalApi::class, ExperimentalWasmInterop::class, UnsafeWasmMemoryApi::class)

      package wit.wasi.clocks.v0_2_12

      import dev.wasmo.brevity.CallBuilder
      import dev.wasmo.brevity.GuestBridge
      import kotlin.Int
      import kotlin.Long
      import kotlin.OptIn
      import kotlin.wasm.ExperimentalWasmInterop
      import kotlin.wasm.unsafe.ComponentModelInternalApi
      import kotlin.wasm.unsafe.Pointer
      import kotlin.wasm.unsafe.UnsafeWasmMemoryApi

      public fun store_WallClock_Instant_guest(
        bridge: GuestBridge,
        address: Pointer,
        value_: WallClock.Instant,
      ) {
        store_WallClock_Datetime_guest(bridge, address, (value_).`value`)
      }

      public fun lowerFlat_WallClock_Instant_guest(
        bridge: GuestBridge,
        value_: WallClock.Instant,
        callBuilder: CallBuilder,
      ) {
        val callBuilder_ = CallBuilder(i32Count = 1, i64Count = 1)
        lowerFlat_WallClock_Datetime_guest(bridge, (value_).`value`, callBuilder_)
        val value__ = callBuilder_.takeI64()
        val value1 = callBuilder_.takeI32()
        callBuilder.put(value__)
        callBuilder.put(value1)
      }

      public fun load_WallClock_Instant_guest(bridge: GuestBridge, address: Pointer): WallClock.Instant = WallClock.Instant(load_WallClock_Datetime_guest(bridge, address))

      public fun liftFlat_WallClock_Instant_guest(
        bridge: GuestBridge,
        value_: Long,
        value1: Int,
      ): WallClock.Instant = WallClock.Instant(liftFlat_WallClock_Datetime_guest(
        bridge,
        value_,
        value1,
      ))

      """.trimIndent(),
    )
  }

  @Test
  fun `type alias host`() {
    assertThat(tester()["wit/wasi/clocks/v0_2_12/WallClockInstantHost.kt".toPath()]).isEqualTo(
      """
      // Generated by Brevity. Do not edit.
      //   clock.wit
      package wit.wasi.clocks.v0_2_12

      import dev.wasmo.brevity.CallBuilder
      import dev.wasmo.brevity.HostBridge
      import kotlin.Int
      import kotlin.Long

      public fun store_WallClock_Instant_host(
        bridge: HostBridge,
        address: Int,
        value_: WallClock.Instant,
      ) {
        store_WallClock_Datetime_host(bridge, address, (value_).`value`)
      }

      public fun lowerFlat_WallClock_Instant_host(
        bridge: HostBridge,
        value_: WallClock.Instant,
        callBuilder: CallBuilder,
      ) {
        val callBuilder_ = CallBuilder(i32Count = 1, i64Count = 1)
        lowerFlat_WallClock_Datetime_host(bridge, (value_).`value`, callBuilder_)
        val value__ = callBuilder_.takeI64()
        val value1 = callBuilder_.takeI32()
        callBuilder.put(value__)
        callBuilder.put(value1)
      }

      public fun load_WallClock_Instant_host(bridge: HostBridge, address: Int): WallClock.Instant = WallClock.Instant(load_WallClock_Datetime_host(bridge, address))

      public fun liftFlat_WallClock_Instant_host(
        bridge: HostBridge,
        value_: Long,
        value1: Int,
      ): WallClock.Instant = WallClock.Instant(liftFlat_WallClock_Datetime_host(
        bridge,
        value_,
        value1,
      ))

      """.trimIndent(),
    )
  }

  @Test
  fun `flags guest`() {
    assertThat(tester()["wit/wasi/clocks/v0_2_12/WallClockPathFlagsGuest.kt".toPath()]).isEqualTo(
      """
      // Generated by Brevity. Do not edit.
      //   clock.wit
      @file:OptIn(ComponentModelInternalApi::class, ExperimentalWasmInterop::class, UnsafeWasmMemoryApi::class)

      package wit.wasi.clocks.v0_2_12

      import dev.wasmo.brevity.GuestBridge
      import kotlin.Int
      import kotlin.OptIn
      import kotlin.wasm.ExperimentalWasmInterop
      import kotlin.wasm.unsafe.ComponentModelInternalApi
      import kotlin.wasm.unsafe.Pointer
      import kotlin.wasm.unsafe.UnsafeWasmMemoryApi

      public fun store_WallClock_PathFlags_guest(
        bridge: GuestBridge,
        address: Pointer,
        value_: WallClock.PathFlags,
      ) {
        // TODO: store wit.wasi.clocks.v0_2_12.WallClock.PathFlags
      }

      public fun lowerFlat_WallClock_PathFlags_guest(bridge: GuestBridge, value_: WallClock.PathFlags): Int = TODO("lower wit.wasi.clocks.v0_2_12.WallClock.PathFlags")

      public fun load_WallClock_PathFlags_guest(bridge: GuestBridge, address: Pointer): WallClock.PathFlags = TODO("load wit.wasi.clocks.v0_2_12.WallClock.PathFlags")

      public fun liftFlat_WallClock_PathFlags_guest(bridge: GuestBridge, value_: Int): WallClock.PathFlags = TODO("lift wit.wasi.clocks.v0_2_12.WallClock.PathFlags")

      """.trimIndent(),
    )
  }

  @Test
  fun `flags host`() {
    assertThat(tester()["wit/wasi/clocks/v0_2_12/WallClockPathFlagsHost.kt".toPath()]).isEqualTo(
      """
      // Generated by Brevity. Do not edit.
      //   clock.wit
      package wit.wasi.clocks.v0_2_12

      import dev.wasmo.brevity.HostBridge
      import kotlin.Int

      public fun store_WallClock_PathFlags_host(
        bridge: HostBridge,
        address: Int,
        value_: WallClock.PathFlags,
      ) {
        // TODO: store wit.wasi.clocks.v0_2_12.WallClock.PathFlags
      }

      public fun lowerFlat_WallClock_PathFlags_host(bridge: HostBridge, value_: WallClock.PathFlags): Int = TODO("lower wit.wasi.clocks.v0_2_12.WallClock.PathFlags")

      public fun load_WallClock_PathFlags_host(bridge: HostBridge, address: Int): WallClock.PathFlags = TODO("load wit.wasi.clocks.v0_2_12.WallClock.PathFlags")

      public fun liftFlat_WallClock_PathFlags_host(bridge: HostBridge, value_: Int): WallClock.PathFlags = TODO("lift wit.wasi.clocks.v0_2_12.WallClock.PathFlags")

      """.trimIndent(),
    )
  }

  @Test
  fun `resource guest`() {
    assertThat(tester()["wit/wasi/clocks/v0_2_12/WallClockPollableGuest.kt".toPath()]).isEqualTo(
      """
      // Generated by Brevity. Do not edit.
      //   clock.wit
      @file:OptIn(ComponentModelInternalApi::class, ExperimentalWasmInterop::class, UnsafeWasmMemoryApi::class)

      package wit.wasi.clocks.v0_2_12

      import dev.wasmo.brevity.GuestBridge
      import kotlin.Boolean
      import kotlin.Int
      import kotlin.OptIn
      import kotlin.wasm.ExperimentalWasmInterop
      import kotlin.wasm.WasmExport
      import kotlin.wasm.WasmImport
      import kotlin.wasm.unsafe.ComponentModelInternalApi
      import kotlin.wasm.unsafe.Pointer
      import kotlin.wasm.unsafe.UnsafeWasmMemoryApi
      import kotlin.wasm.unsafe.freeAllComponentModelReallocAllocatedMemory

      @WasmExport("wasi:clocks/wall-clock@0.2.12#[method]pollable.ready")
      private fun wallClock_pollable_ready_export(self: Int): Int {
        val result = liftFlat_WallClock_Pollable_guest(
          GuestBridge,
          self,
        ).ready(
        )
        return (if (result) 1 else 0)
      }

      @WasmExport("wasi:clocks/wall-clock@0.2.12#[resource-drop]pollable")
      private fun wallClock_pollable_close_export(self: Int) {
        liftFlat_WallClock_Pollable_guest(
          GuestBridge,
          self,
        ).close(
        )
      }

      @WasmImport(
        module = "wasi:clocks/wall-clock@0.2.12",
        name = "[method]pollable.ready",
      )
      private external fun wallClock_pollable_ready_import(self: Int): Int

      @WasmImport(
        module = "wasi:clocks/wall-clock@0.2.12",
        name = "[resource-drop]pollable",
      )
      private external fun wallClock_pollable_close_import(self: Int)

      internal class PollableHandle(
        private val id: Int,
      ) : WallClock.Pollable {
        override fun ready(): Boolean {
          val result = wallClock_pollable_ready_import(
            this.id,
          )
          return (result != 0)
            .also { freeAllComponentModelReallocAllocatedMemory() }
        }

        override fun close() {
          wallClock_pollable_close_import(
            this.id,
          )
        }
      }

      public fun store_WallClock_Pollable_guest(
        bridge: GuestBridge,
        address: Pointer,
        value_: WallClock.Pollable,
      ) {
        (address).storeInt(bridge.toId<WallClock.Pollable>(value_))
      }

      public fun lowerFlat_WallClock_Pollable_guest(bridge: GuestBridge, value_: WallClock.Pollable): Int = bridge.toId<WallClock.Pollable>(value_)

      public fun load_WallClock_Pollable_guest(bridge: GuestBridge, address: Pointer): WallClock.Pollable = bridge.fromId((address).loadInt(), ::PollableHandle)

      public fun liftFlat_WallClock_Pollable_guest(bridge: GuestBridge, value_: Int): WallClock.Pollable = bridge.fromId(value_, ::PollableHandle)

      """.trimIndent(),
    )
  }

  @Test
  fun `resource host`() {
    assertThat(tester()["wit/wasi/clocks/v0_2_12/WallClockPollableHost.kt".toPath()]).isEqualTo(
      """
      // Generated by Brevity. Do not edit.
      //   clock.wit
      package wit.wasi.clocks.v0_2_12

      import dev.wasmo.brevity.HostBridge
      import dev.wasmo.brevity.`get`
      import kotlin.Int

      public fun store_WallClock_Pollable_host(
        bridge: HostBridge,
        address: Int,
        value_: WallClock.Pollable,
      ) {
        bridge.memory.writeI32(address, bridge.toId<WallClock.Pollable>(value_))
      }

      public fun lowerFlat_WallClock_Pollable_host(bridge: HostBridge, value_: WallClock.Pollable): Int = bridge.toId<WallClock.Pollable>(value_)

      public fun load_WallClock_Pollable_host(bridge: HostBridge, address: Int): WallClock.Pollable = bridge.`get`<WallClock.Pollable>(bridge.memory.readInt(address))

      public fun liftFlat_WallClock_Pollable_host(bridge: HostBridge, value_: Int): WallClock.Pollable = bridge.`get`<WallClock.Pollable>(value_)

      """.trimIndent(),
    )
  }
}
