package dev.wasmo.brevity.kotlin.generator

import assertk.assertThat
import assertk.assertions.isEmpty
import assertk.assertions.isEqualTo
import assertk.assertions.isNull
import dev.wasmo.brevity.BrevityTester
import kotlin.test.Test
import okio.Path.Companion.toPath

class KotlinGeneratorTest {

  @Test
  fun `full interface`() {
    val tester = BrevityTester(
      "clock.wit".toPath() to """
        |package wasi:clocks@0.2.12;
        |
        |/// gets the epoch time
        |@since(version = 0.2.0)
        |interface wall-clock {
        |    /// A time and date in seconds plus nanoseconds.
        |    @since(version = 0.2.0)
        |    record datetime {
        |        /// Since 1970.
        |        seconds: u64,
        |        /// Always less than 1000000000.
        |        nanoseconds: u32,
        |    }
        |
        |    /// Read the current value of the clock.
        |    @since(version = 0.2.0)
        |    now: func() -> datetime;
        |
        |    /// `pollable` represents a single I/O event which may be ready, or not.
        |    resource pollable {
        |        /// Return the readiness of a pollable. This function never blocks.
        |        ready: func() -> bool;
        |    }
        |
        |    /// Lookup error codes.
        |    variant error-code {
        |        /// Access denied.
        |        access-denied,
        |        /// A catch-all.
        |        other(option<string>),
        |    }
        |
        |    /// File or memory access pattern advisory information.
        |    enum advice {
        |        /// No advice.
        |        normal,
        |        /// sequentially from lower to higher.
        |        sequential,
        |    }
        |
        |    /// How paths are resolved.
        |    flags path-flags {
        |        /// Follow the darn things.
        |        symlink-follow,
        |    }
        |
        |    /// You can do both with an epoch.
        |    type instant = datetime;
        |}
        """.trimMargin(),
    )

    assertThat(tester["wit/wasi/clocks/v0_2_12/Api.kt".toPath()]).isEqualTo(
      """
      |// Generated by Brevity. Do not edit.
      |//   clock.wit
      |package wit.wasi.clocks.v0_2_12
      |
      |import dev.wasmo.brevity.Resource
      |import kotlin.Boolean
      |import kotlin.String
      |import kotlin.UInt
      |import kotlin.ULong
      |import kotlin.jvm.JvmInline
      |
      |/**
      | * gets the epoch time
      | */
      |public interface WallClock {
      |  /**
      |   * Read the current value of the clock.
      |   */
      |  public fun now(): Datetime
      |
      |  /**
      |   * A time and date in seconds plus nanoseconds.
      |   */
      |  public data class Datetime(
      |    /**
      |     * Since 1970.
      |     */
      |    public val seconds: ULong,
      |    /**
      |     * Always less than 1000000000.
      |     */
      |    public val nanoseconds: UInt,
      |  )
      |
      |  /**
      |   * `pollable` represents a single I/O event which may be ready, or not.
      |   */
      |  public interface Pollable : Resource {
      |    /**
      |     * Return the readiness of a pollable. This function never blocks.
      |     */
      |    public fun ready(): Boolean
      |  }
      |
      |  /**
      |   * Lookup error codes.
      |   */
      |  public sealed interface ErrorCode {
      |    /**
      |     * Access denied.
      |     */
      |    public data object AccessDenied : ErrorCode
      |
      |    /**
      |     * A catch-all.
      |     */
      |    public data class Other(
      |      public val `value`: String?,
      |    ) : ErrorCode
      |  }
      |
      |  /**
      |   * File or memory access pattern advisory information.
      |   */
      |  public enum class Advice {
      |    /**
      |     * No advice.
      |     */
      |    Normal,
      |    /**
      |     * sequentially from lower to higher.
      |     */
      |    Sequential,
      |  }
      |
      |  /**
      |   * How paths are resolved.
      |   */
      |  public data class PathFlags(
      |    /**
      |     * Follow the darn things.
      |     */
      |    public val symlinkFollow: Boolean,
      |  )
      |
      |  /**
      |   * You can do both with an epoch.
      |   */
      |  @JvmInline
      |  public value class Instant(
      |    public val `value`: Datetime,
      |  )
      |}
      |
      """.trimMargin(),
    )

    assertThat(tester["wit/wasi/clocks/v0_2_12/Host.kt".toPath()]).isEqualTo(
      """
      |// Generated by Brevity. Do not edit.
      |//   clock.wit
      |package wit.wasi.clocks.v0_2_12
      |
      |import com.dylibso.chicory.runtime.ExportFunction
      |import dev.wasmo.brevity.HostBridge
      |
      |internal class BridgeWallClock(
      |  private val bridge: HostBridge,
      |) : WallClock {
      |  internal lateinit var now: ExportFunction
      |
      |  override fun now(): WallClock.Datetime {
      |    val result = now.apply(
      |    )
      |    return TODO("lift wit.wasi.clocks.v0_2_12.WallClock.Datetime")
      |  }
      |}
      |
      """.trimMargin(),
    )
  }

  @Test
  fun `full world`() {
    val tester = BrevityTester(
      "command.wit".toPath() to """
        |package wasi:cli@0.3.0;
        |
        |world command {
        |  include imports;
        |  export run;
        |  import args: func() -> list<string>;
        |  import platform: interface {
        |    log: func(message: string);
        |  }
        |}
        """.trimMargin(),

      "exit.wit".toPath() to """
        |interface exit {
        |  exit: func(status: result);
        |}
        """.trimMargin(),

      "imports.wit".toPath() to """
        |package wasi:cli@0.3.0;
        |
        |world imports {
        |  import exit;
        |}
        """.trimMargin(),

      "run.wit".toPath() to """
        |interface run {
        |  run: async func() -> result;
        |}
        """.trimMargin(),
    )

    assertThat(tester["wit/wasi/cli/v0_3_0/Api.kt".toPath()]).isEqualTo(
      """
      |// Generated by Brevity. Do not edit.
      |//   command.wit
      |//   exit.wit
      |//   imports.wit
      |//   run.wit
      |package wit.wasi.cli.v0_3_0
      |
      |import dev.wasmo.brevity.Result
      |import kotlin.String
      |import kotlin.collections.List
      |
      |public interface Platform {
      |  public fun log(message: String)
      |}
      |
      |public object Command {
      |  public interface Guest {
      |    public val run: Run
      |  }
      |
      |  public interface Host {
      |    public val platform: Platform
      |
      |    public val exit: Exit
      |
      |    public fun args(): List<String>
      |  }
      |}
      |
      |public interface Exit {
      |  public fun exit(status: Result<*, *>)
      |}
      |
      |public object Imports {
      |  public interface Host {
      |    public val exit: Exit
      |  }
      |}
      |
      |public interface Run {
      |  public fun run(): Result<*, *>
      |}
      |
      """.trimMargin(),
    )

    assertThat(tester["wit/wasi/cli/v0_3_0/GuestServices.kt".toPath()]).isEqualTo(
      """
      |// Generated by Brevity. Do not edit.
      |//   command.wit
      |//   exit.wit
      |//   imports.wit
      |//   run.wit
      |@file:OptIn(ComponentModelInternalApi::class, ExperimentalWasmInterop::class, UnsafeWasmMemoryApi::class)
      |
      |package wit.wasi.cli.v0_3_0
      |
      |import dev.wasmo.brevity.Result
      |import kotlin.Int
      |import kotlin.OptIn
      |import kotlin.wasm.ExperimentalWasmInterop
      |import kotlin.wasm.WasmExport
      |import kotlin.wasm.unsafe.ComponentModelInternalApi
      |import kotlin.wasm.unsafe.UnsafeWasmMemoryApi
      |
      |private lateinit var guest_: Command.Guest
      |
      |public var Command.guest: Command.Guest
      |  get() = guest_
      |  set(`value`) {
      |    guest_ = `value`
      |  }
      |
      |@WasmExport("wasi:cli/run@0.3.0#run")
      |private fun run_run_export(): Int {
      |  val result = guest_.run.run(
      |  )
      |  val variant = result
      |  val discriminator = when (variant) {
      |    is Result.Ok -> {
      |      0
      |    }
      |    is Result.Error -> {
      |      1
      |    }
      |  }
      |  return discriminator
      |}
      |
      """.trimMargin(),
    )

    assertThat(tester["wit/wasi/cli/v0_3_0/GuestTypes.kt".toPath()]).isNull()

    assertThat(tester["wit/wasi/cli/v0_3_0/Host.kt".toPath()]).isEqualTo(
      """
      |// Generated by Brevity. Do not edit.
      |//   command.wit
      |//   exit.wit
      |//   imports.wit
      |//   run.wit
      |package wit.wasi.cli.v0_3_0
      |
      |import com.dylibso.chicory.runtime.ExportFunction
      |import com.dylibso.chicory.runtime.HostFunction
      |import com.dylibso.chicory.runtime.Instance
      |import com.dylibso.chicory.runtime.Store
      |import com.dylibso.chicory.runtime.WasmFunctionHandle
      |import com.dylibso.chicory.wasm.types.FunctionType
      |import com.dylibso.chicory.wasm.types.ValType
      |import dev.wasmo.brevity.HostBridge
      |import dev.wasmo.brevity.Result
      |import dev.wasmo.brevity.World
      |import kotlin.String
      |import kotlin.Unit
      |import kotlin.collections.List
      |import kotlin.text.encodeToByteArray
      |
      |internal class BridgePlatform(
      |  private val bridge: HostBridge,
      |) : Platform {
      |  internal lateinit var log: ExportFunction
      |
      |  override fun log(message: String) {
      |    val byteArray = message.encodeToByteArray()
      |    val stringAddress = bridge.allocate(byteArray.size)
      |    bridge.memory.write(stringAddress, byteArray)
      |    log.apply(
      |      stringAddress.toLong(),
      |      byteArray.size.toLong(),
      |    )
      |  }
      |}
      |
      |public fun Command.World(hostFactory: (Command.Guest) -> Command.Host): World<Command.Host, Command.Guest> {
      |  val bridge = HostBridge()
      |  val guest = BridgeCommand.BridgeGuest(bridge)
      |  val host = hostFactory(guest)
      |  return BridgeCommand(bridge, guest, host)
      |}
      |
      |internal class BridgeCommand(
      |  private val bridge: HostBridge,
      |  override val guest: BridgeGuest,
      |  override val host: Command.Host,
      |) : World<Command.Host, Command.Guest> {
      |  override fun initExports(instance: Instance) {
      |    this.bridge.init(instance)
      |    guest.run.run = instance.export("wasi:cli/run@0.3.0#run")
      |  }
      |
      |  override fun initImports(store: Store) {
      |    store.addFunction(
      |      HostFunction(
      |        null,
      |        "args",
      |        FunctionType.of(
      |          listOf(ValType.I32),
      |          listOf(),
      |        ),
      |        WasmFunctionHandle { instance, args ->
      |          val self = host
      |          val result = self.args()
      |          val resultParameter = args[0].toInt()
      |          val listAddress = bridge.allocate(result.size * 8)
      |          for (i in result.indices) {
      |            val elementAddress = listAddress + i * 8
      |            val byteArray = result[i].encodeToByteArray()
      |            val stringAddress = bridge.allocate(byteArray.size)
      |            bridge.memory.write(stringAddress, byteArray)
      |            val stringAddress_ = stringAddress
      |            val stringByteCount = byteArray.size
      |            bridge.memory.writeI32(elementAddress, stringAddress_)
      |            bridge.memory.writeI32(elementAddress + 4, stringByteCount)
      |          }
      |          bridge.memory.writeI32(resultParameter, listAddress)
      |          bridge.memory.writeI32(resultParameter + 4, result.size)
      |          return@WasmFunctionHandle longArrayOf()
      |        },
      |      )
      |    )
      |    store.addFunction(
      |      HostFunction(
      |        "wasi:cli/platform@0.3.0",
      |        "log",
      |        FunctionType.of(
      |          listOf(ValType.I32, ValType.I32),
      |          listOf(),
      |        ),
      |        WasmFunctionHandle { instance, args ->
      |          val self = host.platform
      |          self.log(
      |            message = bridge.memory.readString(args[0].toInt(), args[1].toInt()),
      |          )
      |          return@WasmFunctionHandle longArrayOf()
      |        },
      |      )
      |    )
      |    store.addFunction(
      |      HostFunction(
      |        "wasi:cli/exit@0.3.0",
      |        "exit",
      |        FunctionType.of(
      |          listOf(ValType.I32),
      |          listOf(),
      |        ),
      |        WasmFunctionHandle { instance, args ->
      |          val variant = when (args[0].toInt()) {
      |            0 -> {
      |              Result.Ok<Unit, Unit>(kotlin.Unit)
      |            }
      |            1 -> {
      |              Result.Error<Unit, Unit>(kotlin.Unit)
      |            }
      |            else -> error("unexpected case")
      |          }
      |          val self = host.exit
      |          self.exit(
      |            status = variant,
      |          )
      |          return@WasmFunctionHandle longArrayOf()
      |        },
      |      )
      |    )
      |  }
      |
      |  internal class BridgeGuest(
      |    private val bridge: HostBridge,
      |  ) : Command.Guest {
      |    override val run: BridgeRun = BridgeRun(bridge)
      |  }
      |
      |  internal class BridgeHost(
      |    private val bridge: HostBridge,
      |  ) : Command.Host {
      |    internal lateinit var args: ExportFunction
      |
      |    override val platform: BridgePlatform = BridgePlatform(bridge)
      |
      |    override val exit: BridgeExit = BridgeExit(bridge)
      |
      |    override fun args(): List<String> {
      |      val result = args.apply(
      |      )
      |      val listAddress = bridge.memory.readInt(result[0].toInt())
      |      val length = bridge.memory.readInt(result[0].toInt() + 4)
      |      val list = List<String>(length) { i ->
      |        val elementAddress = listAddress + i * 8
      |        val stringAddress = bridge.memory.readInt(elementAddress)
      |        val stringByteCount = bridge.memory.readInt(elementAddress + 4)
      |        bridge.memory.readString(stringAddress, stringByteCount)
      |      }
      |      return list
      |    }
      |  }
      |}
      |
      |internal class BridgeExit(
      |  private val bridge: HostBridge,
      |) : Exit {
      |  internal lateinit var exit: ExportFunction
      |
      |  override fun exit(status: Result<*, *>) {
      |    val variant = status
      |    val discriminator = when (variant) {
      |      is Result.Ok -> {
      |        0
      |      }
      |      is Result.Error -> {
      |        1
      |      }
      |    }
      |    exit.apply(
      |      discriminator.toLong(),
      |    )
      |  }
      |}
      |
      |public fun Imports.World(hostFactory: (Unit) -> Imports.Host): World<Imports.Host, Unit> {
      |  val bridge = HostBridge()
      |  val guest = Unit
      |  val host = hostFactory(guest)
      |  return BridgeImports(bridge, guest, host)
      |}
      |
      |internal class BridgeImports(
      |  private val bridge: HostBridge,
      |  override val guest: Unit,
      |  override val host: Imports.Host,
      |) : World<Imports.Host, Unit> {
      |  override fun initExports(instance: Instance) {
      |    this.bridge.init(instance)
      |  }
      |
      |  override fun initImports(store: Store) {
      |    store.addFunction(
      |      HostFunction(
      |        "wasi:cli/exit@0.3.0",
      |        "exit",
      |        FunctionType.of(
      |          listOf(ValType.I32),
      |          listOf(),
      |        ),
      |        WasmFunctionHandle { instance, args ->
      |          val variant = when (args[0].toInt()) {
      |            0 -> {
      |              Result.Ok<Unit, Unit>(kotlin.Unit)
      |            }
      |            1 -> {
      |              Result.Error<Unit, Unit>(kotlin.Unit)
      |            }
      |            else -> error("unexpected case")
      |          }
      |          val self = host.exit
      |          self.exit(
      |            status = variant,
      |          )
      |          return@WasmFunctionHandle longArrayOf()
      |        },
      |      )
      |    )
      |  }
      |
      |  internal class BridgeHost(
      |    private val bridge: HostBridge,
      |  ) : Imports.Host {
      |    override val exit: BridgeExit = BridgeExit(bridge)
      |  }
      |}
      |
      |internal class BridgeRun(
      |  private val bridge: HostBridge,
      |) : Run {
      |  internal lateinit var run: ExportFunction
      |
      |  override fun run(): Result<*, *> {
      |    val result = run.apply(
      |    )
      |    val variant = when (result[0].toInt()) {
      |      0 -> {
      |        Result.Ok<Unit, Unit>(kotlin.Unit)
      |      }
      |      1 -> {
      |        Result.Error<Unit, Unit>(kotlin.Unit)
      |      }
      |      else -> error("unexpected case")
      |    }
      |    return variant
      |  }
      |}
      |
      """.trimMargin(),
    )
  }

  @Test
  fun `world function`() {
    val tester = BrevityTester(
      "command.wit".toPath() to """
        |package wasi:cli@0.3.0;
        |
        |world command {
        |  export run: func(args: list<string>) -> s32;
        |}
        """.trimMargin(),
    )

    assertThat(tester["wit/wasi/cli/v0_3_0/Api.kt".toPath()]).isEqualTo(
      """
      |// Generated by Brevity. Do not edit.
      |//   command.wit
      |package wit.wasi.cli.v0_3_0
      |
      |import kotlin.Int
      |import kotlin.String
      |import kotlin.collections.List
      |
      |public object Command {
      |  public interface Guest {
      |    public fun run(args: List<String>): Int
      |  }
      |}
      |
      """.trimMargin(),
    )
    assertThat(tester["wit/wasi/cli/v0_3_0/GuestServices.kt".toPath()]).isEqualTo(
      """
      |// Generated by Brevity. Do not edit.
      |//   command.wit
      |@file:OptIn(ComponentModelInternalApi::class, ExperimentalWasmInterop::class, UnsafeWasmMemoryApi::class)
      |
      |package wit.wasi.cli.v0_3_0
      |
      |import dev.wasmo.brevity.loadString
      |import kotlin.Int
      |import kotlin.OptIn
      |import kotlin.String
      |import kotlin.collections.List
      |import kotlin.wasm.ExperimentalWasmInterop
      |import kotlin.wasm.WasmExport
      |import kotlin.wasm.unsafe.ComponentModelInternalApi
      |import kotlin.wasm.unsafe.Pointer
      |import kotlin.wasm.unsafe.UnsafeWasmMemoryApi
      |
      |private lateinit var guest_: Command.Guest
      |
      |public var Command.guest: Command.Guest
      |  get() = guest_
      |  set(`value`) {
      |    guest_ = `value`
      |  }
      |
      |@WasmExport("run")
      |private fun run_export(argsAddress: Int, argsSize: Int): Int {
      |  val listAddress = Pointer(argsAddress.toUInt())
      |  val length = argsSize
      |  val list = List<String>(length) { i ->
      |    val elementAddress = listAddress + i * 8
      |    val stringAddress = elementAddress.loadInt()
      |    val stringByteCount = (elementAddress + 4).loadInt()
      |    Pointer(stringAddress.toUInt()).loadString(stringByteCount)
      |  }
      |  val result = guest_.run(
      |    args = list,
      |  )
      |  return result
      |}
      |
      """.trimMargin(),
    )

    assertThat(tester["wit/wasi/cli/v0_3_0/GuestTypes.kt".toPath()]).isNull()

    assertThat(tester["wit/wasi/cli/v0_3_0/Host.kt".toPath()]).isEqualTo(
      """
      |// Generated by Brevity. Do not edit.
      |//   command.wit
      |package wit.wasi.cli.v0_3_0
      |
      |import com.dylibso.chicory.runtime.ExportFunction
      |import com.dylibso.chicory.runtime.Instance
      |import com.dylibso.chicory.runtime.Store
      |import dev.wasmo.brevity.HostBridge
      |import dev.wasmo.brevity.World
      |import kotlin.Int
      |import kotlin.String
      |import kotlin.Unit
      |import kotlin.collections.List
      |import kotlin.text.encodeToByteArray
      |
      |public fun Command.World(hostFactory: (Command.Guest) -> Unit): World<Unit, Command.Guest> {
      |  val bridge = HostBridge()
      |  val guest = BridgeCommand.BridgeGuest(bridge)
      |  val host = hostFactory(guest)
      |  return BridgeCommand(bridge, guest, host)
      |}
      |
      |internal class BridgeCommand(
      |  private val bridge: HostBridge,
      |  override val guest: BridgeGuest,
      |  override val host: Unit,
      |) : World<Unit, Command.Guest> {
      |  override fun initExports(instance: Instance) {
      |    this.bridge.init(instance)
      |    guest.run = instance.export("run")
      |  }
      |
      |  override fun initImports(store: Store) {
      |  }
      |
      |  internal class BridgeGuest(
      |    private val bridge: HostBridge,
      |  ) : Command.Guest {
      |    internal lateinit var run: ExportFunction
      |
      |    override fun run(args: List<String>): Int {
      |      val listAddress = bridge.allocate(args.size * 8)
      |      for (i in args.indices) {
      |        val elementAddress = listAddress + i * 8
      |        val byteArray = args[i].encodeToByteArray()
      |        val stringAddress = bridge.allocate(byteArray.size)
      |        bridge.memory.write(stringAddress, byteArray)
      |        val stringAddress_ = stringAddress
      |        val stringByteCount = byteArray.size
      |        bridge.memory.writeI32(elementAddress, stringAddress_)
      |        bridge.memory.writeI32(elementAddress + 4, stringByteCount)
      |      }
      |      val result = run.apply(
      |        listAddress.toLong(),
      |        args.size.toLong(),
      |      )
      |      return result[0].toInt()
      |    }
      |  }
      |}
      |
      """.trimMargin(),
    )
  }

  /** We had a bug where we used the wrong package name when following includes across packages. */
  @Test
  fun `imports across packages`() {
    val tester = BrevityTester(
      "cli/command.wit".toPath() to """
        |package wasi:cli@0.3.0;
        |
        |world command {
        |  import wasi:clocks/monotonic-clock@0.3.0;
        |}
        """.trimMargin(),

      "clocks/clock.wit".toPath() to """
        |package wasi:clocks@0.3.0;
        |
        |interface monotonic-clock {
        |  now: func() -> s64;
        |}
        """.trimMargin(),
    )

    assertThat(tester["wit/wasi/cli/v0_3_0/Api.kt".toPath()]).isEqualTo(
      """
      |// Generated by Brevity. Do not edit.
      |//   cli/command.wit
      |package wit.wasi.cli.v0_3_0
      |
      |import wit.wasi.clocks.v0_3_0.MonotonicClock
      |
      |public object Command {
      |  public interface Host {
      |    public val monotonicClock: MonotonicClock
      |  }
      |}
      |
      """.trimMargin(),
    )

    assertThat(tester["wit/wasi/clocks/v0_3_0/Api.kt".toPath()]).isEqualTo(
      """
      |// Generated by Brevity. Do not edit.
      |//   clocks/clock.wit
      |package wit.wasi.clocks.v0_3_0
      |
      |import kotlin.Long
      |
      |public interface MonotonicClock {
      |  public fun now(): Long
      |}
      |
      """.trimMargin(),
    )

    assertThat(tester["wit/wasi/cli/v0_3_0/Host.kt".toPath()]).isEqualTo(
      """
      |// Generated by Brevity. Do not edit.
      |//   cli/command.wit
      |package wit.wasi.cli.v0_3_0
      |
      |import com.dylibso.chicory.runtime.HostFunction
      |import com.dylibso.chicory.runtime.Instance
      |import com.dylibso.chicory.runtime.Store
      |import com.dylibso.chicory.runtime.WasmFunctionHandle
      |import com.dylibso.chicory.wasm.types.FunctionType
      |import com.dylibso.chicory.wasm.types.ValType
      |import dev.wasmo.brevity.HostBridge
      |import dev.wasmo.brevity.World
      |import kotlin.Unit
      |import wit.wasi.clocks.v0_3_0.BridgeMonotonicClock
      |
      |public fun Command.World(hostFactory: (Unit) -> Command.Host): World<Command.Host, Unit> {
      |  val bridge = HostBridge()
      |  val guest = Unit
      |  val host = hostFactory(guest)
      |  return BridgeCommand(bridge, guest, host)
      |}
      |
      |internal class BridgeCommand(
      |  private val bridge: HostBridge,
      |  override val guest: Unit,
      |  override val host: Command.Host,
      |) : World<Command.Host, Unit> {
      |  override fun initExports(instance: Instance) {
      |    this.bridge.init(instance)
      |  }
      |
      |  override fun initImports(store: Store) {
      |    store.addFunction(
      |      HostFunction(
      |        "wasi:clocks/monotonic-clock@0.3.0",
      |        "now",
      |        FunctionType.of(
      |          listOf(),
      |          listOf(ValType.I64),
      |        ),
      |        WasmFunctionHandle { instance, args ->
      |          val self = host.monotonicClock
      |          val result = self.now()
      |          return@WasmFunctionHandle longArrayOf(result)
      |        },
      |      )
      |    )
      |  }
      |
      |  internal class BridgeHost(
      |    private val bridge: HostBridge,
      |  ) : Command.Host {
      |    override val monotonicClock: BridgeMonotonicClock = BridgeMonotonicClock(bridge)
      |  }
      |}
      |
      """.trimMargin(),
    )

    assertThat(tester["wit/wasi/clocks/v0_3_0/Host.kt".toPath()]).isEqualTo(
      """
      |// Generated by Brevity. Do not edit.
      |//   clocks/clock.wit
      |package wit.wasi.clocks.v0_3_0
      |
      |import com.dylibso.chicory.runtime.ExportFunction
      |import dev.wasmo.brevity.HostBridge
      |import kotlin.Long
      |
      |internal class BridgeMonotonicClock(
      |  private val bridge: HostBridge,
      |) : MonotonicClock {
      |  internal lateinit var now: ExportFunction
      |
      |  override fun now(): Long {
      |    val result = now.apply(
      |    )
      |    return result[0]
      |  }
      |}
      |
      """.trimMargin(),
    )
  }

  /**
   * Don't declare a property for imported interfaces that don't declare any functions. Otherwise,
   * we may get a collision declaring multiple mutually-redundant `types` members.
   */
  @Test
  fun `imports of interfaces without functions are skipped`() {
    val tester = BrevityTester(
      "sockets.wit".toPath() to """
        |package wasi:sockets@0.3.0;
        |
        |@since(version = 0.3.0)
        |world imports {
        |    @since(version = 0.3.0)
        |    import types;
        |}
        """.trimMargin(),

      "types.wit".toPath() to """
        |interface types {
        |    type ipv4-address = tuple<u8, u8, u8, u8>;
        |    type ipv6-address = tuple<u16, u16, u16, u16, u16, u16, u16, u16>;
        |
        |    variant ip-address {
        |        ipv4(ipv4-address),
        |        ipv6(ipv6-address),
        |    }
        |}
        """.trimMargin(),
    )

    assertThat(tester["wit/wasi/sockets/v0_3_0/Api.kt".toPath()]).isEqualTo(
      """
      |// Generated by Brevity. Do not edit.
      |//   sockets.wit
      |//   types.wit
      |package wit.wasi.sockets.v0_3_0
      |
      |import dev.wasmo.brevity.Quad
      |import kotlin.UByte
      |import kotlin.collections.List
      |import kotlin.jvm.JvmInline
      |
      |public object Types {
      |  @JvmInline
      |  public value class Ipv4Address(
      |    public val `value`: Quad<UByte, UByte, UByte, UByte>,
      |  )
      |
      |  @JvmInline
      |  public value class Ipv6Address(
      |    public val `value`: List<*>,
      |  )
      |
      |  public sealed interface IpAddress {
      |    public data class Ipv4(
      |      public val `value`: Ipv4Address,
      |    ) : IpAddress
      |
      |    public data class Ipv6(
      |      public val `value`: Ipv6Address,
      |    ) : IpAddress
      |  }
      |}
      |
      """.trimMargin(),
    )
    assertThat(tester.guestFiles).isEmpty()
    assertThat(tester.hostFiles).isEmpty()
  }

  @Test
  fun `resource bridging`() {
    val tester = BrevityTester(
      "testing.wit".toPath() to """
        |package namespace:package-name;
        |
        |world test {
        |  resource person {
        |    get-name: func() -> string;
        |    replace-name: func(name: string) -> string;
        |  }
        |
        |  export greet: func(recipient: person) -> string;
        |}
        """.trimMargin(),
    )

    assertThat(tester["wit/namespace/package_name/Api.kt".toPath()]).isEqualTo(
      """
      |// Generated by Brevity. Do not edit.
      |//   testing.wit
      |package wit.namespace.package_name
      |
      |import dev.wasmo.brevity.Resource
      |import kotlin.String
      |
      |public object Test {
      |  public interface Person : Resource {
      |    public fun getName(): String
      |
      |    public fun replaceName(name: String): String
      |  }
      |
      |  public interface Guest {
      |    public fun greet(recipient: Person): String
      |  }
      |}
      |
      """.trimMargin(),
    )

    assertThat(tester["wit/namespace/package_name/GuestServices.kt".toPath()]).isEqualTo(
      """
      |// Generated by Brevity. Do not edit.
      |//   testing.wit
      |@file:OptIn(ComponentModelInternalApi::class, ExperimentalWasmInterop::class, UnsafeWasmMemoryApi::class)
      |
      |package wit.namespace.package_name
      |
      |import dev.wasmo.brevity.GuestBridge
      |import dev.wasmo.brevity.storeByteArray
      |import kotlin.Int
      |import kotlin.OptIn
      |import kotlin.text.encodeToByteArray
      |import kotlin.wasm.ExperimentalWasmInterop
      |import kotlin.wasm.WasmExport
      |import kotlin.wasm.unsafe.ComponentModelInternalApi
      |import kotlin.wasm.unsafe.UnsafeWasmMemoryApi
      |import kotlin.wasm.unsafe.withScopedMemoryAllocator
      |
      |private lateinit var guest_: Test.Guest
      |
      |public var Test.guest: Test.Guest
      |  get() = guest_
      |  set(`value`) {
      |    guest_ = `value`
      |  }
      |
      |@WasmExport("greet")
      |private fun greet_export(recipient: Int): Int {
      |  withScopedMemoryAllocator { memoryAllocator ->
      |    val result = guest_.greet(
      |      recipient = GuestBridge.fromId(recipient, ::PersonHandle),
      |    )
      |    val resultAddress = memoryAllocator.allocate(8)
      |    val byteArray = result.encodeToByteArray()
      |    val stringAddress = memoryAllocator.allocate(byteArray.size)
      |    stringAddress.storeByteArray(byteArray)
      |    val stringAddress_ = stringAddress.address.toInt()
      |    val stringByteCount = byteArray.size
      |    resultAddress.storeInt(stringAddress_)
      |    (resultAddress + 4).storeInt(stringByteCount)
      |    return resultAddress.address.toInt()
      |  }
      |}
      |
      """.trimMargin(),
    )

    assertThat(tester["wit/namespace/package_name/GuestTypes.kt".toPath()]).isEqualTo(
      """
      |// Generated by Brevity. Do not edit.
      |//   testing.wit
      |@file:OptIn(ComponentModelInternalApi::class, ExperimentalWasmInterop::class, UnsafeWasmMemoryApi::class)
      |
      |package wit.namespace.package_name
      |
      |import dev.wasmo.brevity.loadString
      |import dev.wasmo.brevity.storeByteArray
      |import kotlin.Int
      |import kotlin.OptIn
      |import kotlin.String
      |import kotlin.text.encodeToByteArray
      |import kotlin.wasm.ExperimentalWasmInterop
      |import kotlin.wasm.WasmImport
      |import kotlin.wasm.unsafe.ComponentModelInternalApi
      |import kotlin.wasm.unsafe.Pointer
      |import kotlin.wasm.unsafe.UnsafeWasmMemoryApi
      |import kotlin.wasm.unsafe.freeAllComponentModelReallocAllocatedMemory
      |import kotlin.wasm.unsafe.withScopedMemoryAllocator
      |
      |@WasmImport(
      |  module = "namespace:package-name/test",
      |  name = "[method]person.get-name",
      |)
      |private external fun test_person_getName_import(self: Int, resultParameter: Int)
      |
      |@WasmImport(
      |  module = "namespace:package-name/test",
      |  name = "[method]person.replace-name",
      |)
      |private external fun test_person_replaceName_import(
      |  self: Int,
      |  namePointer: Int,
      |  nameByteCount: Int,
      |  resultParameter: Int,
      |)
      |
      |@WasmImport(
      |  module = "namespace:package-name/test",
      |  name = "[resource-drop]person",
      |)
      |private external fun test_person_close_import(self: Int)
      |
      |internal class PersonHandle(
      |  private val id: Int,
      |) : Test.Person {
      |  override fun getName(): String {
      |    withScopedMemoryAllocator { memoryAllocator ->
      |      val resultParameter = memoryAllocator.allocate(8)
      |      test_person_getName_import(
      |        this.id,
      |        resultParameter.address.toInt(),
      |      )
      |      val stringAddress = resultParameter.loadInt()
      |      val stringByteCount = (resultParameter + 4).loadInt()
      |      return Pointer(stringAddress.toUInt()).loadString(stringByteCount)
      |        .also { freeAllComponentModelReallocAllocatedMemory() }
      |    }
      |  }
      |
      |  override fun replaceName(name: String): String {
      |    withScopedMemoryAllocator { memoryAllocator ->
      |      val byteArray = name.encodeToByteArray()
      |      val stringAddress = memoryAllocator.allocate(byteArray.size)
      |      stringAddress.storeByteArray(byteArray)
      |      val resultParameter = memoryAllocator.allocate(8)
      |      test_person_replaceName_import(
      |        this.id,
      |        stringAddress.address.toInt(),
      |        byteArray.size,
      |        resultParameter.address.toInt(),
      |      )
      |      val stringAddress_ = resultParameter.loadInt()
      |      val stringByteCount = (resultParameter + 4).loadInt()
      |      return Pointer(stringAddress_.toUInt()).loadString(stringByteCount)
      |        .also { freeAllComponentModelReallocAllocatedMemory() }
      |    }
      |  }
      |
      |  override fun close() {
      |    test_person_close_import(
      |      this.id,
      |    )
      |  }
      |}
      |
      """.trimMargin(),
    )

    assertThat(tester["wit/namespace/package_name/Host.kt".toPath()]).isEqualTo(
      """
      |// Generated by Brevity. Do not edit.
      |//   testing.wit
      |package wit.namespace.package_name
      |
      |import com.dylibso.chicory.runtime.ExportFunction
      |import com.dylibso.chicory.runtime.HostFunction
      |import com.dylibso.chicory.runtime.Instance
      |import com.dylibso.chicory.runtime.Store
      |import com.dylibso.chicory.runtime.WasmFunctionHandle
      |import com.dylibso.chicory.wasm.types.FunctionType
      |import com.dylibso.chicory.wasm.types.ValType
      |import dev.wasmo.brevity.HostBridge
      |import dev.wasmo.brevity.World
      |import dev.wasmo.brevity.`get`
      |import kotlin.String
      |import kotlin.Unit
      |import kotlin.text.encodeToByteArray
      |
      |public fun Test.World(hostFactory: (Test.Guest) -> Unit): World<Unit, Test.Guest> {
      |  val bridge = HostBridge()
      |  val guest = BridgeTest.BridgeGuest(bridge)
      |  val host = hostFactory(guest)
      |  return BridgeTest(bridge, guest, host)
      |}
      |
      |internal class BridgeTest(
      |  private val bridge: HostBridge,
      |  override val guest: BridgeGuest,
      |  override val host: Unit,
      |) : World<Unit, Test.Guest> {
      |  override fun initExports(instance: Instance) {
      |    this.bridge.init(instance)
      |    guest.greet = instance.export("greet")
      |  }
      |
      |  override fun initImports(store: Store) {
      |    store.addFunction(
      |      HostFunction(
      |        "namespace:package-name/test",
      |        "[method]person.get-name",
      |        FunctionType.of(
      |          listOf(ValType.I32, ValType.I32),
      |          listOf(),
      |        ),
      |        WasmFunctionHandle { instance, args ->
      |          val self = bridge.`get`<Test.Person>(args[0].toInt())
      |          val result = self.getName()
      |          val resultParameter = args[1].toInt()
      |          val byteArray = result.encodeToByteArray()
      |          val stringAddress = bridge.allocate(byteArray.size)
      |          bridge.memory.write(stringAddress, byteArray)
      |          val stringAddress_ = stringAddress
      |          val stringByteCount = byteArray.size
      |          bridge.memory.writeI32(resultParameter, stringAddress_)
      |          bridge.memory.writeI32(resultParameter + 4, stringByteCount)
      |          return@WasmFunctionHandle longArrayOf()
      |        },
      |      )
      |    )
      |    store.addFunction(
      |      HostFunction(
      |        "namespace:package-name/test",
      |        "[method]person.replace-name",
      |        FunctionType.of(
      |          listOf(ValType.I32, ValType.I32, ValType.I32, ValType.I32),
      |          listOf(),
      |        ),
      |        WasmFunctionHandle { instance, args ->
      |          val self = bridge.`get`<Test.Person>(args[0].toInt())
      |          val result = self.replaceName(
      |            name = bridge.memory.readString(args[1].toInt(), args[2].toInt()),
      |          )
      |          val resultParameter = args[3].toInt()
      |          val byteArray = result.encodeToByteArray()
      |          val stringAddress = bridge.allocate(byteArray.size)
      |          bridge.memory.write(stringAddress, byteArray)
      |          val stringAddress_ = stringAddress
      |          val stringByteCount = byteArray.size
      |          bridge.memory.writeI32(resultParameter, stringAddress_)
      |          bridge.memory.writeI32(resultParameter + 4, stringByteCount)
      |          return@WasmFunctionHandle longArrayOf()
      |        },
      |      )
      |    )
      |    store.addFunction(
      |      HostFunction(
      |        "namespace:package-name/test",
      |        "[resource-drop]person",
      |        FunctionType.of(
      |          listOf(ValType.I32),
      |          listOf(),
      |        ),
      |        WasmFunctionHandle { instance, args ->
      |          val self = bridge.`get`<Test.Person>(args[0].toInt())
      |          self.close()
      |          return@WasmFunctionHandle longArrayOf()
      |        },
      |      )
      |    )
      |  }
      |
      |  internal class BridgeGuest(
      |    private val bridge: HostBridge,
      |  ) : Test.Guest {
      |    internal lateinit var greet: ExportFunction
      |
      |    override fun greet(recipient: Test.Person): String {
      |      val result = greet.apply(
      |        bridge.toId<Test.Person>(recipient).toLong(),
      |      )
      |      val stringAddress = bridge.memory.readInt(result[0].toInt())
      |      val stringByteCount = bridge.memory.readInt(result[0].toInt() + 4)
      |      return bridge.memory.readString(stringAddress, stringByteCount)
      |    }
      |  }
      |}
      |
      """.trimMargin(),
    )
  }
}
