package dev.wasmo.brevity.kotlin.generator

import assertk.assertThat
import assertk.assertions.isEqualTo
import com.squareup.kotlinpoet.ClassName
import com.squareup.kotlinpoet.FunSpec
import com.squareup.kotlinpoet.KModifier
import com.squareup.kotlinpoet.PropertySpec
import com.squareup.kotlinpoet.STRING
import com.squareup.kotlinpoet.TypeSpec
import dev.wasmo.brevity.Location
import dev.wasmo.brevity.kotlin.generator.QualifiedSpec.SourceSet
import kotlin.test.Test
import okio.Path.Companion.toPath

class ProjectSpecTest {
  private val resort = ClassName("dev.wasmo", "Resort")
  private val cafe = resort.nestedClass("Cafe")
  private val spa = resort.nestedClass("Spa")
  private val sauna = spa.nestedClass("Sauna")
  private val heater = sauna.nestedClass("Heater")
  private val locations = setOf(Location("island.wit".toPath()))

  @Test
  fun happyPath() {
    val list = mutableListOf<QualifiedSpec>()
    list.collect(
      sourceSet = SourceSet.CommonMain,
      locations = locations,
      packageName = resort.packageName,
      fileName = "Island",
    ) {
      contextOf<QualifiedSpecCollector>().addType(
        className = resort,
        type = TypeSpec.classBuilder(resort).build(),
      )
      contextOf<QualifiedSpecCollector>().addType(
        className = spa,
        type = TypeSpec.classBuilder(spa).build(),
      )
      contextOf<QualifiedSpecCollector>() += FunSpec.builder("snorkel").build()
      contextOf<QualifiedSpecCollector>() +=
        PropertySpec.builder("Aulani", resort, KModifier.LATEINIT)
          .mutable(true)
          .build()
    }

    val project = ProjectSpec(list)
    val fileSpecs = project.fileSpecs(SourceSet.CommonMain)
    assertThat(fileSpecs.single().toString()).isEqualTo(
      """
      // Generated by Brevity. Do not edit.
      //   island.wit
      package dev.wasmo

      public class Resort {
        public class Spa
      }

      public fun snorkel() {
      }

      public lateinit var Aulani: Resort

      """.trimIndent(),
    )
  }

  /** Confirm we can add functions and properties to types. */
  @Test
  fun classMembers() {
    val list = mutableListOf<QualifiedSpec>()
    list.add(
      QualifiedSpec.Type(
        parent = QualifiedSpec.Parent.File(SourceSet.CommonMain, resort.packageName, "Island"),
        className = resort,
        type = TypeSpec.interfaceBuilder(resort).build(),
      ),
    )
    list.add(
      QualifiedSpec.Property(
        parent = QualifiedSpec.Parent.Type(SourceSet.CommonMain, resort),
        property = PropertySpec.builder("name", STRING).build(),
      ),
    )
    list.add(
      QualifiedSpec.Function(
        parent = QualifiedSpec.Parent.Type(SourceSet.CommonMain, resort),
        function = FunSpec.builder("book").addModifiers(KModifier.ABSTRACT).build(),
      ),
    )

    val project = ProjectSpec(list)
    val fileSpecs = project.fileSpecs(SourceSet.CommonMain)
    assertThat(fileSpecs.single().toString()).isEqualTo(
      """
      // Generated by Brevity. Do not edit.
      package dev.wasmo

      import kotlin.String

      public interface Resort {
        public val name: String

        public fun book()
      }

      """.trimIndent(),
    )
  }

  /** Confirm we build the right tree structure from unsorted inputs. */
  @Test
  fun nestedMembers() {
    val list = mutableListOf<QualifiedSpec>()
    list.add(
      QualifiedSpec.Type(
        parent = QualifiedSpec.Parent.File(SourceSet.CommonMain, resort.packageName, "Island"),
        className = resort,
        type = TypeSpec.interfaceBuilder(resort).build(),
      ),
    )
    list.add(
      QualifiedSpec.Type(
        parent = QualifiedSpec.Parent.Type(SourceSet.CommonMain, spa),
        className = sauna,
        type = TypeSpec.interfaceBuilder(sauna).build(),
      ),
    )
    list.add(
      QualifiedSpec.Type(
        parent = QualifiedSpec.Parent.Type(SourceSet.CommonMain, resort),
        className = spa,
        type = TypeSpec.interfaceBuilder(spa).build(),
      ),
    )
    list.add(
      QualifiedSpec.Type(
        parent = QualifiedSpec.Parent.Type(SourceSet.CommonMain, sauna),
        className = heater,
        type = TypeSpec.interfaceBuilder(heater).build(),
      ),
    )

    val project = ProjectSpec(list)
    val fileSpecs = project.fileSpecs(SourceSet.CommonMain)
    assertThat(fileSpecs.single().toString()).isEqualTo(
      """
      // Generated by Brevity. Do not edit.
      package dev.wasmo

      public interface Resort {
        public interface Spa {
          public interface Sauna {
            public interface Heater
          }
        }
      }

      """.trimIndent(),
    )
  }

  /** Confirm we aggregate paths and opt-ins from child specs. */
  @Test
  fun multipleChildren() {
    val list = mutableListOf<QualifiedSpec>()
    list.add(
      QualifiedSpec.Type(
        parent = QualifiedSpec.Parent.File(SourceSet.CommonMain, resort.packageName, "Island"),
        optIns = setOf(ClassName("dev.wasmo", "ExperimentalIsland")),
        className = resort,
        type = TypeSpec.interfaceBuilder(resort).build(),
      ),
    )
    list.add(
      QualifiedSpec.Type(
        parent = QualifiedSpec.Parent.Type(SourceSet.CommonMain, resort),
        locations = setOf(Location("spa.wit".toPath())),
        className = spa,
        type = TypeSpec.interfaceBuilder(spa).build(),
      ),
    )
    list.add(
      QualifiedSpec.Type(
        parent = QualifiedSpec.Parent.Type(SourceSet.CommonMain, resort),
        locations = setOf(Location("cafe.wit".toPath())),
        optIns = setOf(ClassName("dev.wasmo", "ExperimentalCoffee")),
        className = cafe,
        type = TypeSpec.interfaceBuilder(cafe).build(),
      ),
    )

    val project = ProjectSpec(list)
    val fileSpecs = project.fileSpecs(SourceSet.CommonMain)
    assertThat(fileSpecs.single().toString()).isEqualTo(
      """
      // Generated by Brevity. Do not edit.
      //   cafe.wit
      //   spa.wit
      @file:OptIn(ExperimentalCoffee::class, ExperimentalIsland::class)

      package dev.wasmo

      import dev.wasmo.ExperimentalCoffee
      import dev.wasmo.ExperimentalIsland
      import kotlin.OptIn

      public interface Resort {
        public interface Spa

        public interface Cafe
      }

      """.trimIndent(),
    )
  }
}
