[workspace]
members = [
  "content-type",
  "http",
  "jobs",
  "json",
  "object-store",
  "platform",
  "sql",
  "transfer-service",
  "uuid",
]

[workspace.metadata]
authors = "Wasmolians <noreply@wasmo.com>"
license = "Apache-2.0"
repository = "https://github.com/wasmcomputercompany/brevity/"
