[workspace]
members = [
  "outer-space",
  "hyperspace",
]

[workspace.metadata]
authors = "Wasmo Contributors <noreply@wasmo.com>"
license = "Apache-2.0"
repository = "https://github.com/wasmcomputercompany/brevity/"
